/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AuditLogResponse } from "./auditLogResponse";

/**
 * Paginated list of audit logs.
 */
export interface AuditLogListResponse {
  items: AuditLogResponse[];
  limit: number;
  page: number;
  pages: number;
  total: number;
}
