/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AuditLogResponseActorEmail } from "./auditLogResponseActorEmail";
import type { AuditLogResponseActorId } from "./auditLogResponseActorId";
import type { AuditLogResponseActorIp } from "./auditLogResponseActorIp";
import type { AuditLogResponseChanges } from "./auditLogResponseChanges";
import type { AuditLogResponseMetadata } from "./auditLogResponseMetadata";
import type { AuditLogResponseRequestMethod } from "./auditLogResponseRequestMethod";
import type { AuditLogResponseRequestPath } from "./auditLogResponseRequestPath";
import type { AuditLogResponseResourceId } from "./auditLogResponseResourceId";
import type { AuditLogResponseResourceName } from "./auditLogResponseResourceName";
import type { AuditLogResponseResourceType } from "./auditLogResponseResourceType";
import type { AuditLogResponseStatusCode } from "./auditLogResponseStatusCode";

/**
 * Response for a single audit log entry.
 */
export interface AuditLogResponse {
  action: string;
  actor_email?: AuditLogResponseActorEmail;
  actor_id?: AuditLogResponseActorId;
  actor_ip?: AuditLogResponseActorIp;
  changes?: AuditLogResponseChanges;
  id: string;
  metadata?: AuditLogResponseMetadata;
  request_method?: AuditLogResponseRequestMethod;
  request_path?: AuditLogResponseRequestPath;
  resource_id?: AuditLogResponseResourceId;
  resource_name?: AuditLogResponseResourceName;
  resource_type?: AuditLogResponseResourceType;
  status_code?: AuditLogResponseStatusCode;
  timestamp: string;
}
