/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ColumnLineageResponseTransformation } from "./columnLineageResponseTransformation";

/**
 * Response for column lineage.
 */
export interface ColumnLineageResponse {
  confidence?: number;
  source_column: string;
  source_dataset: string;
  target_column: string;
  target_dataset: string;
  transformation?: ColumnLineageResponseTransformation;
}
