/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type CreateUserRequestRole =
  (typeof CreateUserRequestRole)[keyof typeof CreateUserRequestRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserRequestRole = {
  admin: "admin",
  member: "member",
  viewer: "viewer",
} as const;
