/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CreateInvestigationRequestMetadata } from "./createInvestigationRequestMetadata";

/**
 * Request body for creating an investigation.
 */
export interface CreateInvestigationRequest {
  actual_value: number;
  anomaly_date: string;
  dataset_id: string;
  deviation_pct: number;
  expected_value: number;
  metadata?: CreateInvestigationRequestMetadata;
  metric_name: string;
  severity?: string;
}
