/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CreateApiKeyRequestExpiresInDays } from "./createApiKeyRequestExpiresInDays";

/**
 * Request to create an API key.
 */
export interface CreateApiKeyRequest {
  expires_in_days?: CreateApiKeyRequestExpiresInDays;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  scopes?: string[];
}
