/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CreateApprovalRequestContext } from "./createApprovalRequestContext";

/**
 * Request to create a new approval request.
 */
export interface CreateApprovalRequest {
  context: CreateApprovalRequestContext;
  investigation_id: string;
  /** @pattern ^(context_review|query_approval|execution_approval)$ */
  request_type: string;
}
