/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DatasetResponseDatabase } from "./datasetResponseDatabase";
import type { DatasetResponseDescription } from "./datasetResponseDescription";
import type { DatasetResponseSchema } from "./datasetResponseSchema";
import type { DatasetResponseSourceCodePath } from "./datasetResponseSourceCodePath";
import type { DatasetResponseSourceCodeUrl } from "./datasetResponseSourceCodeUrl";

/**
 * Response for a dataset.
 */
export interface DatasetResponse {
  database?: DatasetResponseDatabase;
  dataset_type: string;
  description?: DatasetResponseDescription;
  id: string;
  name: string;
  owners?: string[];
  platform: string;
  qualified_name: string;
  schema?: DatasetResponseSchema;
  source_code_path?: DatasetResponseSourceCodePath;
  source_code_url?: DatasetResponseSourceCodeUrl;
  tags?: string[];
}
