/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DataSourceResponseLastHealthCheckAt } from "./dataSourceResponseLastHealthCheckAt";

/**
 * Response for a data source.
 */
export interface DataSourceResponse {
  category: string;
  created_at: string;
  id: string;
  is_active: boolean;
  is_default: boolean;
  last_health_check_at?: DataSourceResponseLastHealthCheckAt;
  name: string;
  status: string;
  type: string;
}
