/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DatasetSummaryCatalogName } from "./datasetSummaryCatalogName";
import type { DatasetSummaryColumnCount } from "./datasetSummaryColumnCount";
import type { DatasetSummaryLastSyncedAt } from "./datasetSummaryLastSyncedAt";
import type { DatasetSummaryRowCount } from "./datasetSummaryRowCount";
import type { DatasetSummarySchemaName } from "./datasetSummarySchemaName";

/**
 * Summary of a dataset for list responses.
 */
export interface DatasetSummary {
  catalog_name?: DatasetSummaryCatalogName;
  column_count?: DatasetSummaryColumnCount;
  created_at: string;
  datasource_id: string;
  id: string;
  last_synced_at?: DatasetSummaryLastSyncedAt;
  name: string;
  native_path: string;
  row_count?: DatasetSummaryRowCount;
  schema_name?: DatasetSummarySchemaName;
  table_type: string;
}
