/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ExportAuditLogsApiV1AuditLogsExportGetParams = {
  start_date?: string | null;
  end_date?: string | null;
  action?: string | null;
  actor_id?: string | null;
  resource_type?: string | null;
  search?: string | null;
};
