/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type FeedbackCreateTargetType =
  (typeof FeedbackCreateTargetType)[keyof typeof FeedbackCreateTargetType];

export const FeedbackCreateTargetType = {
  hypothesis: "hypothesis",
  query: "query",
  evidence: "evidence",
  synthesis: "synthesis",
  investigation: "investigation",
} as const;
