/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type FeedbackCreateRating =
  (typeof FeedbackCreateRating)[keyof typeof FeedbackCreateRating];

export const FeedbackCreateRating = {
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;
