/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type GetDownstreamApiV1LineageDownstreamGetParams = {
  /**
   * Dataset identifier (platform://name)
   */
  dataset: string;
  /**
   * Depth of lineage traversal
   */
  depth?: number;
  /**
   * Lineage provider to use
   */
  provider?: string;
  /**
   * Path to dbt manifest.json
   */
  manifest_path?: string | null;
  /**
   * Base URL for API-based providers
   */
  base_url?: string | null;
};
