/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type GetLineageGraphApiV1LineageGraphGetParams = {
  /**
   * Dataset identifier (platform://name)
   */
  dataset: string;
  /**
   * Upstream traversal depth
   */
  upstream_depth?: number;
  /**
   * Downstream traversal depth
   */
  downstream_depth?: number;
  /**
   * Lineage provider to use
   */
  provider?: string;
  /**
   * Path to dbt manifest.json
   */
  manifest_path?: string | null;
  /**
   * Base URL for API-based providers
   */
  base_url?: string | null;
};
