/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { JobRunResponseDurationSeconds } from "./jobRunResponseDurationSeconds";
import type { JobRunResponseEndedAt } from "./jobRunResponseEndedAt";
import type { JobRunResponseErrorMessage } from "./jobRunResponseErrorMessage";
import type { JobRunResponseLogsUrl } from "./jobRunResponseLogsUrl";

/**
 * Response for a job run.
 */
export interface JobRunResponse {
  duration_seconds?: JobRunResponseDurationSeconds;
  ended_at?: JobRunResponseEndedAt;
  error_message?: JobRunResponseErrorMessage;
  id: string;
  job_id: string;
  logs_url?: JobRunResponseLogsUrl;
  started_at: string;
  status: string;
}
