/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { JobResponseSourceCodePath } from "./jobResponseSourceCodePath";
import type { JobResponseSourceCodeUrl } from "./jobResponseSourceCodeUrl";

/**
 * Response for a job.
 */
export interface JobResponse {
  id: string;
  inputs?: string[];
  job_type: string;
  name: string;
  outputs?: string[];
  source_code_path?: JobResponseSourceCodePath;
  source_code_url?: JobResponseSourceCodeUrl;
}
