/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { LineageProviderResponseCapabilities } from "./lineageProviderResponseCapabilities";
import type { LineageProviderResponseConfigSchema } from "./lineageProviderResponseConfigSchema";

/**
 * Response for a lineage provider definition.
 */
export interface LineageProviderResponse {
  capabilities: LineageProviderResponseCapabilities;
  config_schema: LineageProviderResponseConfigSchema;
  description: string;
  display_name: string;
  provider: string;
}
