/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { LineageProviderConfigConfig } from "./lineageProviderConfigConfig";

/**
 * Configuration for a lineage provider.
 */
export interface LineageProviderConfig {
  /** Provider-specific configuration */
  config?: LineageProviderConfigConfig;
  /**
   * Priority for composite adapters (higher = preferred)
   * @minimum 1
   * @maximum 100
   */
  priority?: number;
  /** Provider type (dbt, openlineage, airflow, dagster, datahub, static_sql) */
  provider: string;
}
