/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { LineageEdgeResponseJobId } from "./lineageEdgeResponseJobId";

/**
 * Response for a lineage edge.
 */
export interface LineageEdgeResponse {
  edge_type?: string;
  job_id?: LineageEdgeResponseJobId;
  source: string;
  target: string;
}
