/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { MetricSpecRequestSourceUrl } from "./metricSpecRequestSourceUrl";

/**
 * Structured metric specification from upstream anomaly detector.
 */
export interface MetricSpecRequest {
  columns_referenced?: string[];
  display_name: string;
  expression: string;
  metric_type: string;
  source_url?: MetricSpecRequestSourceUrl;
}
