/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { NotificationResponseBody } from "./notificationResponseBody";
import type { NotificationResponseReadAt } from "./notificationResponseReadAt";
import type { NotificationResponseResourceId } from "./notificationResponseResourceId";
import type { NotificationResponseResourceKind } from "./notificationResponseResourceKind";

/**
 * Single notification response.
 */
export interface NotificationResponse {
  body: NotificationResponseBody;
  created_at: string;
  id: string;
  read_at: NotificationResponseReadAt;
  resource_id: NotificationResponseResourceId;
  resource_kind: NotificationResponseResourceKind;
  severity: string;
  title: string;
  type: string;
}
