/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Password reset confirmation body.
 */
export interface PasswordResetConfirm {
  /** @minLength 8 */
  new_password: string;
  token: string;
}
