/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type PermissionGrantCreateAccessType =
  (typeof PermissionGrantCreateAccessType)[keyof typeof PermissionGrantCreateAccessType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionGrantCreateAccessType = {
  resource: "resource",
  tag: "tag",
  datasource: "datasource",
} as const;
