/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type PermissionGrantCreatePermission =
  (typeof PermissionGrantCreatePermission)[keyof typeof PermissionGrantCreatePermission];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionGrantCreatePermission = {
  read: "read",
  write: "write",
  admin: "admin",
} as const;
