/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type PermissionGrantCreateGranteeType =
  (typeof PermissionGrantCreateGranteeType)[keyof typeof PermissionGrantCreateGranteeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionGrantCreateGranteeType = {
  user: "user",
  team: "team",
} as const;
