/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { QueryResponseColumnsItem } from "./queryResponseColumnsItem";
import type { QueryResponseExecutionTimeMs } from "./queryResponseExecutionTimeMs";
import type { QueryResponseRowsItem } from "./queryResponseRowsItem";

/**
 * Response for query execution.
 */
export interface QueryResponse {
  columns: QueryResponseColumnsItem[];
  execution_time_ms?: QueryResponseExecutionTimeMs;
  row_count: number;
  rows: QueryResponseRowsItem[];
  truncated?: boolean;
}
