/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { RecentInvestigationSeverity } from "./recentInvestigationSeverity";

/**
 * Summary of a recent investigation.
 */
export interface RecentInvestigation {
  created_at: string;
  dataset_id: string;
  id: string;
  metric_name: string;
  severity?: RecentInvestigationSeverity;
  status: string;
}
