/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { RecoveryMethodResponseActionUrl } from "./recoveryMethodResponseActionUrl";
import type { RecoveryMethodResponseAdminEmail } from "./recoveryMethodResponseAdminEmail";

/**
 * Recovery method response.
 */
export interface RecoveryMethodResponse {
  action_url?: RecoveryMethodResponseActionUrl;
  admin_email?: RecoveryMethodResponseAdminEmail;
  message: string;
  type: string;
}
