/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Token refresh request body.
 */
export interface RefreshRequest {
  org_id: string;
  refresh_token: string;
}
