/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Request to reject an investigation.
 */
export interface RejectRequest {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  reason: string;
}
