/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SchemaResponseModelCatalogsItem } from "./schemaResponseModelCatalogsItem";

/**
 * Response for schema discovery.
 */
export interface SchemaResponseModel {
  catalogs: SchemaResponseModelCatalogsItem[];
  fetched_at: string;
  source_category: string;
  source_id: string;
  source_type: string;
}
