/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SCIMUserCreateRequestDisplayName } from "./sCIMUserCreateRequestDisplayName";
import type { SCIMUserCreateRequestEmails } from "./sCIMUserCreateRequestEmails";
import type { SCIMUserCreateRequestExternalId } from "./sCIMUserCreateRequestExternalId";
import type { SCIMUserCreateRequestName } from "./sCIMUserCreateRequestName";

/**
 * SCIM user creation request.
 */
export interface SCIMUserCreateRequest {
  active?: boolean;
  displayName?: SCIMUserCreateRequestDisplayName;
  emails?: SCIMUserCreateRequestEmails;
  externalId?: SCIMUserCreateRequestExternalId;
  name?: SCIMUserCreateRequestName;
  schemas: string[];
  userName: string;
}
