/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { StartInvestigationRequestAlert } from "./startInvestigationRequestAlert";

/**
 * Request body for starting an investigation.
 */
export interface StartInvestigationRequest {
  alert: StartInvestigationRequestAlert;
}
