/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TagUpdateColor } from "./tagUpdateColor";
import type { TagUpdateName } from "./tagUpdateName";

/**
 * Tag update request.
 */
export interface TagUpdate {
  color?: TagUpdateColor;
  name?: TagUpdateName;
}
