/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TeamResponseExternalId } from "./teamResponseExternalId";
import type { TeamResponseMemberCount } from "./teamResponseMemberCount";

/**
 * Team response.
 */
export interface TeamResponse {
  external_id: TeamResponseExternalId;
  id: string;
  is_scim_managed: boolean;
  member_count?: TeamResponseMemberCount;
  name: string;
}
