/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Team response model.
 */
export interface TeamResponse {
  created_at: string;
  id: string;
  name: string;
  org_id: string;
}
