/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { LineageProviderConfig } from "./lineageProviderConfig";
import type { TenantSettingsNotificationEmail } from "./tenantSettingsNotificationEmail";
import type { TenantSettingsSlackChannel } from "./tenantSettingsSlackChannel";

/**
 * Tenant-level settings.
 */
export interface TenantSettings {
  /** Configured lineage providers for this tenant */
  lineage_providers?: LineageProviderConfig[];
  max_queries_per_investigation?: number;
  name: string;
  notification_email?: TenantSettingsNotificationEmail;
  require_approval_for_queries?: boolean;
  slack_channel?: TenantSettingsSlackChannel;
  slug: string;
}
