/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TokenResponseOrg } from "./tokenResponseOrg";
import type { TokenResponseRefreshToken } from "./tokenResponseRefreshToken";
import type { TokenResponseRole } from "./tokenResponseRole";
import type { TokenResponseUser } from "./tokenResponseUser";

/**
 * Token response.
 */
export interface TokenResponse {
  access_token: string;
  org?: TokenResponseOrg;
  refresh_token?: TokenResponseRefreshToken;
  role?: TokenResponseRole;
  token_type?: string;
  user?: TokenResponseUser;
}
