/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { UpdateUserRequestIsActive } from "./updateUserRequestIsActive";
import type { UpdateUserRequestName } from "./updateUserRequestName";
import type { UpdateUserRequestRole } from "./updateUserRequestRole";

/**
 * Request to update a user.
 */
export interface UpdateUserRequest {
  is_active?: UpdateUserRequestIsActive;
  name?: UpdateUserRequestName;
  role?: UpdateUserRequestRole;
}
