/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { UserResponseName } from "./userResponseName";
import type { UserResponseRole } from "./userResponseRole";

/**
 * Response for a user.
 */
export interface UserResponse {
  created_at: string;
  email: string;
  id: string;
  is_active: boolean;
  name?: UserResponseName;
  role: UserResponseRole;
}
