/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { UserResponse } from "./userResponse";

/**
 * Response for listing users.
 */
export interface UserListResponse {
  total: number;
  users: UserResponse[];
}
