/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type UserResponseRole =
  (typeof UserResponseRole)[keyof typeof UserResponseRole];


export const UserResponseRole = {
  admin: "admin",
  member: "member",
  viewer: "viewer",
} as const;
