/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * 1 for upvote, -1 for downvote
 */
export type VoteCreateVote =
  (typeof VoteCreateVote)[keyof typeof VoteCreateVote];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoteCreateVote = {
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;
