/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response after creating a webhook with secret.
 */
export interface WebhookCreatedResponse {
  events: string[];
  id: string;
  secret: string;
  url: string;
}
