/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { WebhookResponseLastStatus } from "./webhookResponseLastStatus";
import type { WebhookResponseLastTriggeredAt } from "./webhookResponseLastTriggeredAt";

/**
 * Response for a webhook.
 */
export interface WebhookResponse {
  created_at: string;
  events: string[];
  id: string;
  is_active: boolean;
  last_status?: WebhookResponseLastStatus;
  last_triggered_at?: WebhookResponseLastTriggeredAt;
  url: string;
}
