// API types - These would normally be generated by Orval from OpenAPI spec

export interface CreateInvestigationRequest {
  dataset_id: string
  metric_name: string
  expected_value: number
  actual_value: number
  deviation_pct: number
  anomaly_date: string
  severity?: string
  metadata?: Record<string, string | number | boolean>
}

export interface InvestigationResponse {
  investigation_id: string
  status: string
  created_at: string
}

export interface InvestigationEvent {
  type: string
  timestamp: string
  data: Record<string, unknown>
}

export interface InvestigationFinding {
  investigation_id: string
  status: string
  root_cause: string | null
  confidence: number
  evidence: Evidence[]
  recommendations: string[]
  duration_seconds: number
}

export interface Evidence {
  hypothesis_id: string
  query: string
  result_summary: string
  row_count: number
  supports_hypothesis: boolean | null
  confidence: number
  interpretation: string
}

export interface InvestigationStatusResponse {
  investigation_id: string
  status: string
  events: InvestigationEvent[]
  finding: InvestigationFinding | null
}

export interface InvestigationListItem {
  investigation_id: string
  status: string
  created_at: string
  dataset_id: string
}
