"""Response models for investigation agents.

These models define the exact schema expected from the LLM.
Pydantic AI uses these for:
1. Generating schema hints in the prompt
2. Validating LLM responses
3. Automatic retry on validation failure
"""

from __future__ import annotations

from typing import Literal

import sqlglot
from pydantic import BaseModel, Field, field_validator, model_validator

from dataing.core.domain_types import HypothesisCategory
from dataing.core.exceptions import QueryValidationError
from dataing.safety.validator import validate_query as _validate_query_safety

# Fix type literals
FixType = Literal["sql_ddl", "sql_dml", "dbt_patch", "python_patch", "manual_instruction"]

# SQL statement types for validation
DDL_STATEMENTS = {"ALTER", "CREATE", "DROP"}
DML_STATEMENTS = {"INSERT", "UPDATE", "DELETE", "MERGE"}


def _strip_markdown(query: str) -> str:
    """Strip markdown code blocks from query.

    Handles various markdown formats:
    - ```sql ... ```
    - ```SQL ... ```
    - ```postgresql ... ```
    - Unclosed code blocks (just opening ```)
    """
    if query.startswith("```"):
        lines = query.strip().split("\n")
        # Handle both closed and unclosed blocks
        if lines[-1] == "```":
            return "\n".join(lines[1:-1])
        return "\n".join(lines[1:])
    return query


def _validate_sql_query(
    query: str,
    *,
    require_select: bool = False,
    dialect: str = "postgres",
) -> str:
    """Validate SQL query using sqlglot. Returns stripped query.

    Args:
        query: The SQL query (may include markdown code blocks).
        require_select: If True, query must be a SELECT statement.
        dialect: SQL dialect for parsing.

    Returns:
        The stripped and validated query string.

    Raises:
        ValueError: If query is invalid (Pydantic-compatible error).
    """
    stripped = _strip_markdown(query).strip()
    if not stripped:
        raise ValueError("Empty query after stripping markdown")

    try:
        _validate_query_safety(stripped, dialect=dialect, require_select=require_select)
    except QueryValidationError as e:
        raise ValueError(str(e)) from None

    return stripped


class HypothesisResponse(BaseModel):
    """Single hypothesis from the LLM."""

    id: str = Field(description="Unique identifier like 'h1', 'h2', etc.")
    title: str = Field(
        description="Short, specific title describing the potential cause",
        min_length=10,
        max_length=200,
    )
    category: HypothesisCategory = Field(description="Classification of the hypothesis type")
    reasoning: str = Field(
        description="Explanation of why this could be the cause",
        min_length=20,
    )
    suggested_query: str = Field(
        description="SQL query to investigate this hypothesis. Must include LIMIT clause.",
    )
    expected_if_true: str = Field(
        description="What results we expect if this hypothesis is correct",
        min_length=10,
    )
    expected_if_false: str = Field(
        description="What results we expect if this hypothesis is wrong",
        min_length=10,
    )

    @field_validator("suggested_query")
    @classmethod
    def validate_query_safety(cls, v: str) -> str:
        """Validate query safety: strip markdown, require LIMIT, block mutations."""
        return _validate_sql_query(v, require_select=False)


class HypothesesResponse(BaseModel):
    """Container for multiple hypotheses."""

    hypotheses: list[HypothesisResponse] = Field(
        description="List of hypotheses to investigate",
        min_length=1,
        max_length=10,
    )


class QueryResponse(BaseModel):
    """SQL query generated by LLM."""

    query: str = Field(description="The SQL query to execute")
    explanation: str = Field(
        description="Brief explanation of what the query tests",
        default="",
    )

    @field_validator("query")
    @classmethod
    def validate_query(cls, v: str) -> str:
        """Validate the generated SQL."""
        return _validate_sql_query(v, require_select=True)


class InterpretationResponse(BaseModel):
    """LLM interpretation of query results.

    Forces the LLM to articulate cause-and-effect with specific trigger,
    mechanism, and timeline - not just confirm that an issue exists.
    """

    supports_hypothesis: bool | None = Field(
        description="True if evidence supports, False if refutes, None if inconclusive"
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score from 0.0 (no confidence) to 1.0 (certain)",
    )
    interpretation: str = Field(
        description="What the results reveal about the ROOT CAUSE, not just the symptom",
        min_length=50,
    )
    causal_chain: str = Field(
        description=(
            "MUST include: (1) TRIGGER - what changed, (2) MECHANISM - how it caused the symptom, "
            "(3) TIMELINE - when each step occurred. "
            "BAD: 'ETL job failed causing NULLs'. "
            "GOOD: 'API rate limit at 03:14 UTC -> users ETL job timeout after 30s -> "
            "users table missing records after user_id 50847 -> orders JOIN produces NULLs'"
        ),
        min_length=30,
    )
    trigger_identified: str | None = Field(
        default=None,
        description=(
            "The specific trigger that started the causal chain. "
            "Must be concrete: 'API returned 429 at 03:14', 'deploy of commit abc123', "
            "'config change to batch_size'. NOT: 'something failed', 'data corruption occurred'"
        ),
    )
    differentiating_evidence: str | None = Field(
        default=None,
        description=(
            "Evidence that supports THIS hypothesis over alternatives. "
            "What in the data specifically points to this cause and not others? "
            "Example: 'Error code ETL-5012 only appears in users job logs'"
        ),
    )
    key_findings: list[str] = Field(
        description="Specific findings with data points (counts, timestamps, table names)",
        min_length=1,
        max_length=5,
    )
    next_investigation_step: str | None = Field(
        default=None,
        description=(
            "Required if confidence < 0.8 or trigger_identified is empty. "
            "What specific query or check would help identify the trigger?"
        ),
    )


class SynthesisResponse(BaseModel):
    """Final synthesis of investigation findings.

    Requires structured causal chain and impact assessment,
    not just a root cause string.
    """

    root_cause: str | None = Field(
        description=(
            "The UPSTREAM cause, not the symptom. Must explain WHY. "
            "Example: 'users ETL job timed out at 03:14 UTC due to API rate limiting' "
            "NOT: 'NULL user_ids in orders table'"
        )
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence in root cause (0.9+=certain, 0.7-0.9=likely, <0.7=uncertain)",
    )
    causal_chain: list[str] = Field(
        description=(
            "Step-by-step from root cause to observed symptom. "
            "Example: ['API rate limit hit', 'users ETL job timeout', "
            "'users table stale after 03:14', 'orders JOIN produces NULLs']"
        ),
        min_length=2,
        max_length=6,
    )
    estimated_onset: str = Field(
        description="When the issue started (timestamp or relative time, e.g., '03:14 UTC')",
        min_length=5,
    )
    affected_scope: str = Field(
        description="Blast radius: what else is affected? (downstream tables, reports, consumers)",
        min_length=10,
    )
    supporting_evidence: list[str] = Field(
        description="Specific evidence with data points that supports this conclusion",
        min_length=1,
        max_length=10,
    )
    recommendations: list[str] = Field(
        description=(
            "Actionable recommendations with specific targets. "
            "Example: 'Re-run stg_users job: airflow trigger_dag stg_users --backfill' "
            "NOT: 'Investigate the issue'"
        ),
        min_length=1,
        max_length=5,
    )

    @field_validator("root_cause")
    @classmethod
    def validate_root_cause_quality(cls, v: str | None) -> str | None:
        """Ensure root cause is specific enough."""
        if v is not None and len(v) < 20:
            raise ValueError("Root cause description too vague (min 20 chars)")
        return v


class CounterAnalysisResponse(BaseModel):
    """Counter-analysis challenging the synthesis conclusion."""

    alternative_explanations: list[str] = Field(
        description="Other explanations that could fit the same evidence",
        min_length=1,
        max_length=5,
    )
    weaknesses: list[str] = Field(
        description="Specific weaknesses or gaps in the current analysis",
        min_length=1,
        max_length=5,
    )
    confidence_adjustment: float = Field(
        ge=-0.5,
        le=0.5,
        description="Adjustment to confidence (-0.5 to 0.5, negative = weaker)",
    )
    recommendation: str = Field(
        description="One of: 'accept', 'investigate_more', or 'reject'",
    )

    @field_validator("recommendation")
    @classmethod
    def validate_recommendation(cls, v: str) -> str:
        """Ensure recommendation is one of the valid values."""
        valid = {"accept", "investigate_more", "reject"}
        if v not in valid:
            raise ValueError(f"recommendation must be one of {valid}")
        return v


class FixProposal(BaseModel):
    """Proposed fix that the agent can generate after investigation.

    Fix proposals are typed and validated to ensure safety. Each type has
    specific validation rules to prevent dangerous operations.
    """

    fix_type: FixType = Field(
        description=(
            "Type of fix: sql_ddl (ALTER/CREATE/DROP), sql_dml (INSERT/UPDATE/DELETE), "
            "dbt_patch (dbt model change), python_patch (Python code change), "
            "manual_instruction (human action required)"
        )
    )
    description: str = Field(
        description="Human-readable explanation of what the fix does and why",
        min_length=10,
    )
    code: str = Field(
        description="The actual fix code (SQL, dbt YAML/SQL, Python, or instruction text)",
        min_length=1,
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence this fix will resolve the issue (0.0-1.0)",
    )
    risks: list[str] = Field(
        description="Potential negative effects of applying this fix",
        min_length=0,
        max_length=10,
    )
    rollback: str | None = Field(
        default=None,
        description="SQL/code to undo this fix if it causes problems",
    )
    requires_confirmation: bool = Field(
        default=True,
        description="Whether user must confirm before applying (always True for DDL)",
    )
    estimated_impact: str = Field(
        description="Description of affected rows/tables (e.g., 'Affects ~1000 rows in orders')",
        min_length=5,
    )
    target_asset: str = Field(
        description="The table, model, or asset being fixed",
        min_length=1,
    )

    @field_validator("code")
    @classmethod
    def validate_code_not_empty(cls, v: str) -> str:
        """Ensure code is not just whitespace."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("Fix code cannot be empty or whitespace only")
        return v

    @model_validator(mode="after")
    def validate_fix_type_rules(self) -> FixProposal:
        """Validate fix based on its type."""
        code = self.code.strip()

        if self.fix_type == "sql_ddl":
            self._validate_sql_ddl(code)
            # DDL always requires confirmation
            object.__setattr__(self, "requires_confirmation", True)

        elif self.fix_type == "sql_dml":
            self._validate_sql_dml(code)

        elif self.fix_type == "dbt_patch":
            self._validate_dbt_patch(code)

        elif self.fix_type == "python_patch":
            self._validate_python_patch(code)

        # manual_instruction has no code validation - it's just text

        return self

    def _validate_sql_ddl(self, code: str) -> None:
        """Validate SQL DDL statement (ALTER/CREATE/DROP)."""
        try:
            parsed = sqlglot.parse_one(code, dialect="postgres")
        except Exception as e:
            raise ValueError(f"Invalid SQL DDL syntax: {e}") from None

        statement_type = type(parsed).__name__.upper()
        # Map sqlglot types to our DDL statements
        ddl_type_map = {
            "ALTER": {"ALTER"},
            "CREATE": {"CREATE"},
            "DROP": {"DROP"},
        }
        is_ddl = False
        for ddl_keyword, type_names in ddl_type_map.items():
            if any(t in statement_type for t in type_names) or ddl_keyword in statement_type:
                is_ddl = True
                break

        if not is_ddl:
            raise ValueError(
                f"sql_ddl fix must be ALTER, CREATE, or DROP statement, got: {statement_type}"
            )

    def _validate_sql_dml(self, code: str) -> None:
        """Validate SQL DML statement (INSERT/UPDATE/DELETE/MERGE)."""
        try:
            parsed = sqlglot.parse_one(code, dialect="postgres")
        except Exception as e:
            raise ValueError(f"Invalid SQL DML syntax: {e}") from None

        statement_type = type(parsed).__name__.upper()
        is_dml = any(dml in statement_type for dml in DML_STATEMENTS)

        if not is_dml:
            raise ValueError(
                f"sql_dml fix must be INSERT, UPDATE, DELETE, or MERGE statement, "
                f"got: {statement_type}"
            )

    def _validate_dbt_patch(self, code: str) -> None:
        """Validate dbt patch (YAML or SQL)."""
        # dbt patches can be YAML config or SQL model changes
        # Basic validation: must have some structure
        if not code.strip():
            raise ValueError("dbt patch cannot be empty")

        # If it looks like YAML, check for common dbt patterns
        if code.strip().startswith(("-", "version:", "models:", "sources:", "name:")):
            # Looks like YAML - that's fine
            return

        # If contains Jinja templates, skip SQL validation (can't parse {{ }})
        if "{{" in code or "{%" in code:
            return

        # If it looks like SQL without Jinja, validate syntax
        if any(kw in code.upper() for kw in ["SELECT", "WITH", "FROM"]):
            try:
                sqlglot.parse_one(code, dialect="postgres")
            except Exception as e:
                raise ValueError(f"Invalid SQL in dbt patch: {e}") from None

    def _validate_python_patch(self, code: str) -> None:
        """Validate Python code patch."""
        if not code.strip():
            raise ValueError("Python patch cannot be empty")

        # Basic syntax check via compile
        try:
            compile(code, "<fix>", "exec")
        except SyntaxError as e:
            raise ValueError(f"Invalid Python syntax: {e}") from None
