"""Base renderer class for data quality tests."""

from abc import ABC, abstractmethod
from enum import Enum

from dataing.core.codify import DataQualityTest


class RenderFormat(str, Enum):
    """Supported output formats for test rendering."""

    GX = "gx"
    """Great Expectations JSON expectation suite."""

    DBT = "dbt"
    """dbt schema.yml test definition."""

    SODA = "soda"
    """SodaCL check YAML."""

    SQL = "sql"
    """Raw SQL assertion query."""


class BaseRenderer(ABC):
    """Abstract base class for test renderers.

    Renderers convert abstract DataQualityTest objects into concrete
    test definitions for specific frameworks.
    """

    @property
    @abstractmethod
    def format(self) -> RenderFormat:
        """The output format this renderer produces."""
        ...

    @abstractmethod
    def render(self, test: DataQualityTest) -> str:
        """Render a single test to the target format.

        Args:
            test: The abstract test to render.

        Returns:
            The rendered test as a string.
        """
        ...

    def render_many(self, tests: list[DataQualityTest]) -> str:
        """Render multiple tests to the target format.

        Default implementation joins individual renders.
        Subclasses may override for format-specific aggregation.

        Args:
            tests: List of tests to render.

        Returns:
            The rendered tests as a string.
        """
        return "\n\n".join(self.render(test) for test in tests)

    def _format_provenance_comment(self, test: DataQualityTest, prefix: str = "#") -> str:
        """Format a provenance comment for the test.

        Args:
            test: The test to format provenance for.
            prefix: Comment prefix (# for YAML, -- for SQL).

        Returns:
            Formatted provenance comment.
        """
        lines = [
            f"{prefix} Generated by Dataing from investigation {test.source_investigation_id}",
            f"{prefix} {test.name}: {test.description}",
        ]
        if test.failure_description:
            # Truncate long descriptions
            desc = test.failure_description[:80]
            if len(test.failure_description) > 80:
                desc += "..."
            lines.append(f"{prefix} Original issue: {desc}")
        return "\n".join(lines)
