"""dbt renderer for data quality tests."""

from typing import Any

import yaml  # type: ignore[import-untyped]

from dataing.core.codify import AssertionType, DataQualityTest
from dataing.renderers.base import BaseRenderer, RenderFormat


class DbtRenderer(BaseRenderer):
    """Render tests as dbt schema.yml test definitions.

    Outputs YAML compatible with dbt's schema.yml format.
    """

    @property
    def format(self) -> RenderFormat:
        """Return the render format."""
        return RenderFormat.DBT

    def render(self, test: DataQualityTest) -> str:
        """Render a test as dbt schema YAML.

        Args:
            test: The test to render.

        Returns:
            YAML string for the test definition.
        """
        schema = self._build_schema(test)
        yaml_str: str = yaml.dump(schema, default_flow_style=False, sort_keys=False)

        # Add provenance comment
        comment = self._format_provenance_comment(test, prefix="#")
        return f"{comment}\n{yaml_str}"

    def render_many(self, tests: list[DataQualityTest]) -> str:
        """Render multiple tests as a complete dbt schema.yml.

        Groups tests by table for proper schema.yml structure.

        Args:
            tests: Tests to render.

        Returns:
            Complete schema.yml content.
        """
        if not tests:
            result: str = yaml.dump({"version": 2, "models": []}, default_flow_style=False)
            return result

        # Group tests by table
        table_tests: dict[str, list[DataQualityTest]] = {}
        for test in tests:
            table_tests.setdefault(test.table, []).append(test)

        models = []
        for table, table_test_list in table_tests.items():
            model = self._build_model_schema(table, table_test_list)
            models.append(model)

        schema = {"version": 2, "models": models}

        # Add header comment
        investigation_ids = {str(t.source_investigation_id) for t in tests}
        header = [
            "# Generated by Dataing",
            f"# From investigations: {', '.join(sorted(investigation_ids))}",
            "",
        ]

        yaml_str: str = yaml.dump(schema, default_flow_style=False, sort_keys=False)
        return "\n".join(header) + yaml_str

    def _build_schema(self, test: DataQualityTest) -> dict[str, Any]:
        """Build a single model schema for one test.

        Args:
            test: The test to convert.

        Returns:
            Dictionary representing the schema.
        """
        return self._build_model_schema(test.table, [test])

    def _build_model_schema(self, table: str, tests: list[DataQualityTest]) -> dict[str, Any]:
        """Build a model schema with multiple tests.

        Args:
            table: The table name.
            tests: Tests for this table.

        Returns:
            Dictionary representing the model schema.
        """
        # Separate column-level and table-level tests
        column_tests: dict[str, list[dict[str, Any]]] = {}
        table_level_tests: list[dict[str, Any]] = []

        for test in tests:
            dbt_test = self._build_dbt_test(test)
            if test.is_column_level and test.column:
                column_tests.setdefault(test.column, []).append(dbt_test)
            else:
                table_level_tests.append(dbt_test)

        model: dict[str, Any] = {"name": table}

        # Add table-level tests
        if table_level_tests:
            model["tests"] = table_level_tests

        # Add column definitions
        if column_tests:
            columns = []
            for column_name, col_tests in column_tests.items():
                columns.append({"name": column_name, "tests": col_tests})
            model["columns"] = columns

        return model

    def _build_dbt_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build a dbt test definition.

        Args:
            test: The test to convert.

        Returns:
            Dictionary representing the dbt test.
        """
        if test.assertion_type == AssertionType.NOT_NULL:
            return self._not_null_test(test)
        elif test.assertion_type == AssertionType.UNIQUE:
            return self._unique_test(test)
        elif test.assertion_type == AssertionType.ACCEPTED_VALUES:
            return self._accepted_values_test(test)
        elif test.assertion_type == AssertionType.IN_RANGE:
            return self._in_range_test(test)
        elif test.assertion_type == AssertionType.ROW_COUNT_CHANGE:
            return self._row_count_test(test)
        elif test.assertion_type == AssertionType.FRESHNESS:
            return self._freshness_test(test)
        elif test.assertion_type == AssertionType.REFERENTIAL_INTEGRITY:
            return self._referential_test(test)
        elif test.assertion_type == AssertionType.CUSTOM_SQL:
            return self._custom_sql_test(test)
        else:
            return self._fallback_test(test)

    def _severity_config(self, test: DataQualityTest) -> dict[str, str]:
        """Get severity configuration.

        Args:
            test: The test.

        Returns:
            Config dict with severity.
        """
        return {"severity": "error" if test.severity == "fail" else "warn"}

    def _not_null_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build NOT_NULL test."""
        return {"not_null": {"config": self._severity_config(test)}}

    def _unique_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build UNIQUE test."""
        return {"unique": {"config": self._severity_config(test)}}

    def _accepted_values_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build ACCEPTED_VALUES test."""
        values = test.parameters.get("values", [])
        return {
            "accepted_values": {
                "values": values,
                "config": self._severity_config(test),
            }
        }

    def _in_range_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build IN_RANGE test using dbt_expectations."""
        min_val = test.parameters.get("min_value")
        max_val = test.parameters.get("max_value")
        return {
            "dbt_expectations.expect_column_values_to_be_between": {
                "min_value": min_val,
                "max_value": max_val,
                "config": self._severity_config(test),
            }
        }

    def _row_count_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build ROW_COUNT_CHANGE test using dbt_expectations."""
        max_pct = test.parameters.get("max_change_percent", 10)
        return {
            "dbt_expectations.expect_row_count_to_be_within_percent_of_previous_run": {
                "percent": max_pct,
                "config": self._severity_config(test),
            }
        }

    def _freshness_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build FRESHNESS test using dbt source freshness."""
        max_hours = test.parameters.get("max_age_hours", 24)
        min_value = (
            "{{ (modules.datetime.datetime.now() - "
            f"modules.datetime.timedelta(hours={max_hours})).isoformat() }}}}"
        )
        return {
            "dbt_expectations.expect_column_max_to_be_between": {
                "min_value": min_value,
                "row_condition": f"{test.column} is not null",
                "config": self._severity_config(test),
            }
        }

    def _referential_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build REFERENTIAL_INTEGRITY test."""
        ref_table = test.parameters.get("reference_table", "")
        ref_column = test.parameters.get("reference_column", "")
        return {
            "relationships": {
                "to": f"ref('{ref_table}')",
                "field": ref_column,
                "config": self._severity_config(test),
            }
        }

    def _custom_sql_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build CUSTOM_SQL test using dbt generic test."""
        # dbt custom tests go in tests/ directory
        # Here we reference a generic test pattern
        return {
            "dbt_utils.expression_is_true": {
                "expression": f"NOT EXISTS ({test.sql_expression or 'SELECT 1 WHERE FALSE'})",
                "config": self._severity_config(test),
            }
        }

    def _fallback_test(self, test: DataQualityTest) -> dict[str, Any]:
        """Build fallback test for unknown types."""
        return {
            "not_null": {
                "config": {
                    **self._severity_config(test),
                    "meta": {"original_type": test.assertion_type.value},
                }
            }
        }
