"""Great Expectations renderer for data quality tests."""

import json
from typing import Any

from dataing.core.codify import AssertionType, DataQualityTest, ThresholdType
from dataing.renderers.base import BaseRenderer, RenderFormat


class GXRenderer(BaseRenderer):
    """Render tests as Great Expectations expectations.

    Outputs JSON expectation configurations compatible with GX v3 API.
    """

    @property
    def format(self) -> RenderFormat:
        """Return the render format."""
        return RenderFormat.GX

    def render(self, test: DataQualityTest) -> str:
        """Render a test as a GX expectation JSON.

        Args:
            test: The test to render.

        Returns:
            JSON string representing the expectation.
        """
        expectation = self._build_expectation(test)
        return json.dumps(expectation, indent=2)

    def render_many(self, tests: list[DataQualityTest]) -> str:
        """Render multiple tests as a GX expectation suite.

        Args:
            tests: Tests to render.

        Returns:
            JSON string representing the expectation suite.
        """
        if not tests:
            return json.dumps({"expectations": []}, indent=2)

        expectations = [self._build_expectation(test) for test in tests]
        suite = {
            "meta": {
                "generated_by": "dataing",
                "investigation_ids": list({str(t.source_investigation_id) for t in tests}),
            },
            "expectations": expectations,
        }
        return json.dumps(suite, indent=2)

    def render_python(self, test: DataQualityTest) -> str:
        """Render a test as Python code for GX.

        Args:
            test: The test to render.

        Returns:
            Python code string for the expectation.
        """
        expectation = self._build_expectation(test)
        exp_type = expectation["expectation_type"]
        kwargs = expectation["kwargs"]

        lines = [
            f"# Generated by Dataing from investigation {test.source_investigation_id}",
            f"# {test.name}",
            "validator.expect(",
            f'    "{exp_type}",',
        ]

        for key, value in kwargs.items():
            if isinstance(value, str):
                lines.append(f'    {key}="{value}",')
            else:
                lines.append(f"    {key}={value!r},")

        lines.append(")")
        return "\n".join(lines)

    def _build_expectation(self, test: DataQualityTest) -> dict[str, Any]:
        """Build a GX expectation dictionary.

        Args:
            test: The test to convert.

        Returns:
            Dictionary representing the expectation.
        """
        meta = {
            "generated_by": "dataing",
            "investigation_id": str(test.source_investigation_id),
            "test_id": test.test_id,
        }

        if test.assertion_type == AssertionType.NOT_NULL:
            return self._not_null_expectation(test, meta)
        elif test.assertion_type == AssertionType.UNIQUE:
            return self._unique_expectation(test, meta)
        elif test.assertion_type == AssertionType.ACCEPTED_VALUES:
            return self._accepted_values_expectation(test, meta)
        elif test.assertion_type == AssertionType.IN_RANGE:
            return self._in_range_expectation(test, meta)
        elif test.assertion_type == AssertionType.ROW_COUNT_CHANGE:
            return self._row_count_expectation(test, meta)
        elif test.assertion_type == AssertionType.FRESHNESS:
            return self._freshness_expectation(test, meta)
        elif test.assertion_type == AssertionType.REFERENTIAL_INTEGRITY:
            return self._referential_expectation(test, meta)
        elif test.assertion_type == AssertionType.CUSTOM_SQL:
            return self._custom_sql_expectation(test, meta)
        else:
            return self._fallback_expectation(test, meta)

    def _not_null_expectation(self, test: DataQualityTest, meta: dict[str, Any]) -> dict[str, Any]:
        """Build NOT_NULL expectation."""
        kwargs: dict[str, Any] = {"column": test.column}

        # Handle threshold for partial null tolerance
        if test.threshold and test.threshold.threshold_type == ThresholdType.PERCENTAGE:
            # mostly allows a small percentage of nulls
            kwargs["mostly"] = 1.0 - (test.threshold.value / 100.0)

        return {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": kwargs,
            "meta": meta,
        }

    def _unique_expectation(self, test: DataQualityTest, meta: dict[str, Any]) -> dict[str, Any]:
        """Build UNIQUE expectation."""
        return {
            "expectation_type": "expect_column_values_to_be_unique",
            "kwargs": {"column": test.column},
            "meta": meta,
        }

    def _accepted_values_expectation(
        self, test: DataQualityTest, meta: dict[str, Any]
    ) -> dict[str, Any]:
        """Build ACCEPTED_VALUES expectation."""
        values = test.parameters.get("values", [])
        return {
            "expectation_type": "expect_column_values_to_be_in_set",
            "kwargs": {"column": test.column, "value_set": values},
            "meta": meta,
        }

    def _in_range_expectation(self, test: DataQualityTest, meta: dict[str, Any]) -> dict[str, Any]:
        """Build IN_RANGE expectation."""
        min_val = test.parameters.get("min_value")
        max_val = test.parameters.get("max_value")
        return {
            "expectation_type": "expect_column_values_to_be_between",
            "kwargs": {
                "column": test.column,
                "min_value": min_val,
                "max_value": max_val,
            },
            "meta": meta,
        }

    def _row_count_expectation(self, test: DataQualityTest, meta: dict[str, Any]) -> dict[str, Any]:
        """Build ROW_COUNT_CHANGE expectation.

        Note: GX doesn't have a direct row count change expectation.
        We use table_row_count_to_be_between with a placeholder.
        """
        meta["note"] = "Configure min_value and max_value based on expected row count"
        return {
            "expectation_type": "expect_table_row_count_to_be_between",
            "kwargs": {
                "min_value": 1,  # Placeholder
                "max_value": None,  # Placeholder
            },
            "meta": meta,
        }

    def _freshness_expectation(self, test: DataQualityTest, meta: dict[str, Any]) -> dict[str, Any]:
        """Build FRESHNESS expectation.

        Note: GX doesn't have a direct freshness expectation.
        We use column_max_to_be_between with a time constraint.
        """
        max_age_hours = test.parameters.get("max_age_hours", 24)
        meta["note"] = f"Max data age: {max_age_hours} hours"
        return {
            "expectation_type": "expect_column_max_to_be_between",
            "kwargs": {
                "column": test.column,
                # Use GX's strftime format for time comparison
                "min_value": f"{{now - timedelta(hours={max_age_hours})}}",
                "max_value": "{now}",
                "parse_strings_as_datetimes": True,
            },
            "meta": meta,
        }

    def _referential_expectation(
        self, test: DataQualityTest, meta: dict[str, Any]
    ) -> dict[str, Any]:
        """Build REFERENTIAL_INTEGRITY expectation.

        Note: GX requires external reference set.
        """
        ref_table = test.parameters.get("reference_table", "")
        ref_column = test.parameters.get("reference_column", "")
        meta["reference_table"] = ref_table
        meta["reference_column"] = ref_column
        meta["note"] = f"Values should exist in {ref_table}.{ref_column}"
        return {
            "expectation_type": "expect_column_values_to_be_in_set",
            "kwargs": {
                "column": test.column,
                "value_set": f"{{query({ref_table}.{ref_column})}}",
            },
            "meta": meta,
        }

    def _custom_sql_expectation(
        self, test: DataQualityTest, meta: dict[str, Any]
    ) -> dict[str, Any]:
        """Build CUSTOM_SQL expectation."""
        return {
            "expectation_type": "expect_query_to_return_no_rows",
            "kwargs": {"query": test.sql_expression or "SELECT 1 WHERE FALSE"},
            "meta": meta,
        }

    def _fallback_expectation(self, test: DataQualityTest, meta: dict[str, Any]) -> dict[str, Any]:
        """Build a fallback expectation for unknown types."""
        meta["original_type"] = test.assertion_type.value
        return {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {"column": test.column},
            "meta": meta,
        }
