"""Soda renderer for data quality tests."""

from typing import Any

import yaml  # type: ignore[import-untyped]

from dataing.core.codify import AssertionType, DataQualityTest
from dataing.renderers.base import BaseRenderer, RenderFormat


class SodaRenderer(BaseRenderer):
    """Render tests as SodaCL check YAML.

    Outputs YAML compatible with Soda's check format.
    """

    @property
    def format(self) -> RenderFormat:
        """Return the render format."""
        return RenderFormat.SODA

    def render(self, test: DataQualityTest) -> str:
        """Render a test as SodaCL check YAML.

        Args:
            test: The test to render.

        Returns:
            YAML string for the check.
        """
        checks = self._build_checks(test)
        yaml_str = yaml.dump(checks, default_flow_style=False, sort_keys=False)

        # Add provenance comment
        comment = self._format_provenance_comment(test, prefix="#")
        return f"{comment}\n{yaml_str}"

    def render_many(self, tests: list[DataQualityTest]) -> str:
        """Render multiple tests as SodaCL checks.

        Groups checks by table for proper structure.

        Args:
            tests: Tests to render.

        Returns:
            Complete SodaCL checks YAML.
        """
        if not tests:
            return "# No checks generated\n"

        # Group tests by table
        table_tests: dict[str, list[DataQualityTest]] = {}
        for test in tests:
            table_tests.setdefault(test.table, []).append(test)

        # Build checks for each table
        all_checks: dict[str, list[dict[str, Any] | str]] = {}
        for table, table_test_list in table_tests.items():
            checks_key = f"checks for {table}"
            all_checks[checks_key] = []
            for test in table_test_list:
                check = self._build_check(test)
                all_checks[checks_key].append(check)

        # Add header comment
        investigation_ids = {str(t.source_investigation_id) for t in tests}
        header = [
            "# Generated by Dataing",
            f"# From investigations: {', '.join(sorted(investigation_ids))}",
            "",
        ]

        yaml_str: str = yaml.dump(all_checks, default_flow_style=False, sort_keys=False)
        return "\n".join(header) + yaml_str

    def _build_checks(self, test: DataQualityTest) -> dict[str, list[Any]]:
        """Build checks structure for a single test.

        Args:
            test: The test to convert.

        Returns:
            Dictionary with checks for the table.
        """
        check = self._build_check(test)
        return {f"checks for {test.table}": [check]}

    def _build_check(self, test: DataQualityTest) -> dict[str, Any] | str:
        """Build a single SodaCL check.

        Args:
            test: The test to convert.

        Returns:
            Check definition (string for simple, dict for complex).
        """
        if test.assertion_type == AssertionType.NOT_NULL:
            return self._not_null_check(test)
        elif test.assertion_type == AssertionType.UNIQUE:
            return self._unique_check(test)
        elif test.assertion_type == AssertionType.ACCEPTED_VALUES:
            return self._accepted_values_check(test)
        elif test.assertion_type == AssertionType.IN_RANGE:
            return self._in_range_check(test)
        elif test.assertion_type == AssertionType.ROW_COUNT_CHANGE:
            return self._row_count_check(test)
        elif test.assertion_type == AssertionType.FRESHNESS:
            return self._freshness_check(test)
        elif test.assertion_type == AssertionType.REFERENTIAL_INTEGRITY:
            return self._referential_check(test)
        elif test.assertion_type == AssertionType.CUSTOM_SQL:
            return self._custom_sql_check(test)
        else:
            return self._fallback_check(test)

    def _check_name(self, test: DataQualityTest) -> str:
        """Format check name with investigation reference.

        Args:
            test: The test.

        Returns:
            Formatted check name.
        """
        inv_id = str(test.source_investigation_id)[:8]
        return f"{test.name} (from inv_{inv_id})"

    def _not_null_check(self, test: DataQualityTest) -> dict[str, Any]:
        """Build NOT_NULL check."""
        return {
            f"missing_count({test.column}) = 0": {
                "name": self._check_name(test),
            }
        }

    def _unique_check(self, test: DataQualityTest) -> dict[str, Any]:
        """Build UNIQUE check."""
        return {
            f"duplicate_count({test.column}) = 0": {
                "name": self._check_name(test),
            }
        }

    def _accepted_values_check(self, test: DataQualityTest) -> dict[str, Any]:
        """Build ACCEPTED_VALUES check."""
        values = test.parameters.get("values", [])
        return {
            f"invalid_count({test.column}) = 0": {
                "name": self._check_name(test),
                "valid values": values,
                "fail": "when > 0",
                "warn": "when > 0" if test.severity == "warn" else None,
            }
        }

    def _in_range_check(self, test: DataQualityTest) -> dict[str, Any]:
        """Build IN_RANGE check."""
        min_val = test.parameters.get("min_value")
        max_val = test.parameters.get("max_value")
        return {
            f"invalid_count({test.column}) = 0": {
                "name": self._check_name(test),
                "valid min": min_val,
                "valid max": max_val,
            }
        }

    def _row_count_check(self, test: DataQualityTest) -> dict[str, Any]:
        """Build ROW_COUNT_CHANGE check."""
        max_pct = test.parameters.get("max_change_percent", 10)
        return {
            "row_count": {
                "name": self._check_name(test),
                "fail": f"when diff % > {max_pct}",
            }
        }

    def _freshness_check(self, test: DataQualityTest) -> dict[str, Any]:
        """Build FRESHNESS check."""
        max_hours = test.parameters.get("max_age_hours", 24)
        return {
            f"freshness({test.column}) < {int(max_hours)}h": {
                "name": self._check_name(test),
            }
        }

    def _referential_check(self, test: DataQualityTest) -> dict[str, Any]:
        """Build REFERENTIAL_INTEGRITY check."""
        ref_table = test.parameters.get("reference_table", "")
        ref_column = test.parameters.get("reference_column", "")
        return {
            f"reference({test.column}, {ref_table}, {ref_column})": {
                "name": self._check_name(test),
            }
        }

    def _custom_sql_check(self, test: DataQualityTest) -> dict[str, Any]:
        """Build CUSTOM_SQL check."""
        sql = test.sql_expression or "SELECT 1 WHERE FALSE"
        return {
            "failed rows": {
                "name": self._check_name(test),
                "fail query": sql,
            }
        }

    def _fallback_check(self, test: DataQualityTest) -> dict[str, Any]:
        """Build fallback check for unknown types."""
        return {
            f"missing_count({test.column or '*'}) = 0": {
                "name": f"{self._check_name(test)} (fallback)",
            }
        }
