"""SQL renderer for data quality tests."""

from dataing.core.codify import AssertionType, DataQualityTest
from dataing.renderers.base import BaseRenderer, RenderFormat


class SQLRenderer(BaseRenderer):
    """Render tests as raw SQL assertion queries.

    Outputs SQL queries that return rows that FAIL the assertion.
    A passing test returns 0 rows.
    """

    @property
    def format(self) -> RenderFormat:
        """Return the render format."""
        return RenderFormat.SQL

    def render(self, test: DataQualityTest) -> str:
        """Render a test as a SQL assertion query.

        Args:
            test: The test to render.

        Returns:
            SQL query string.
        """
        comment = self._format_provenance_comment(test, prefix="--")
        query = self._build_query(test)
        expected = "-- EXPECTED: 0 rows (any rows returned indicate test failure)"

        return f"{comment}\n{query}\n{expected}"

    def render_many(self, tests: list[DataQualityTest]) -> str:
        """Render multiple tests as SQL queries.

        Args:
            tests: Tests to render.

        Returns:
            SQL queries separated by comments.
        """
        if not tests:
            return "-- No tests generated\n"

        queries = []

        # Add header
        investigation_ids = {str(t.source_investigation_id) for t in tests}
        queries.append("-- Generated by Dataing")
        queries.append(f"-- From investigations: {', '.join(sorted(investigation_ids))}")
        queries.append("")

        for i, test in enumerate(tests, 1):
            queries.append(f"-- Test {i}: {test.name}")
            queries.append(self.render(test))
            queries.append("")

        return "\n".join(queries)

    def _build_query(self, test: DataQualityTest) -> str:
        """Build a SQL assertion query.

        Args:
            test: The test to convert.

        Returns:
            SQL query string.
        """
        if test.assertion_type == AssertionType.NOT_NULL:
            return self._not_null_query(test)
        elif test.assertion_type == AssertionType.UNIQUE:
            return self._unique_query(test)
        elif test.assertion_type == AssertionType.ACCEPTED_VALUES:
            return self._accepted_values_query(test)
        elif test.assertion_type == AssertionType.IN_RANGE:
            return self._in_range_query(test)
        elif test.assertion_type == AssertionType.ROW_COUNT_CHANGE:
            return self._row_count_query(test)
        elif test.assertion_type == AssertionType.FRESHNESS:
            return self._freshness_query(test)
        elif test.assertion_type == AssertionType.REFERENTIAL_INTEGRITY:
            return self._referential_query(test)
        elif test.assertion_type == AssertionType.CUSTOM_SQL:
            return self._custom_sql_query(test)
        else:
            return self._fallback_query(test)

    def _not_null_query(self, test: DataQualityTest) -> str:
        """Build NOT_NULL assertion query."""
        return f"""\
SELECT COUNT(*) AS null_count
FROM {test.table}
WHERE {test.column} IS NULL;"""

    def _unique_query(self, test: DataQualityTest) -> str:
        """Build UNIQUE assertion query."""
        return f"""\
SELECT {test.column}, COUNT(*) AS duplicate_count
FROM {test.table}
WHERE {test.column} IS NOT NULL
GROUP BY {test.column}
HAVING COUNT(*) > 1
LIMIT 100;"""

    def _accepted_values_query(self, test: DataQualityTest) -> str:
        """Build ACCEPTED_VALUES assertion query."""
        values = test.parameters.get("values", [])
        values_str = ", ".join(f"'{v}'" for v in values)
        return f"""\
SELECT {test.column}, COUNT(*) AS invalid_count
FROM {test.table}
WHERE {test.column} NOT IN ({values_str})
  AND {test.column} IS NOT NULL
GROUP BY {test.column}
LIMIT 100;"""

    def _in_range_query(self, test: DataQualityTest) -> str:
        """Build IN_RANGE assertion query."""
        min_val = test.parameters.get("min_value")
        max_val = test.parameters.get("max_value")
        return f"""\
SELECT {test.column}, COUNT(*) AS out_of_range_count
FROM {test.table}
WHERE ({test.column} < {min_val} OR {test.column} > {max_val})
  AND {test.column} IS NOT NULL
GROUP BY {test.column}
LIMIT 100;"""

    def _row_count_query(self, test: DataQualityTest) -> str:
        """Build ROW_COUNT_CHANGE assertion query.

        This is a count query - caller must compare against previous run.
        """
        return f"""\
-- Compare this count against previous run
-- Alert if change exceeds threshold
SELECT COUNT(*) AS current_row_count
FROM {test.table};"""

    def _freshness_query(self, test: DataQualityTest) -> str:
        """Build FRESHNESS assertion query."""
        max_hours = test.parameters.get("max_age_hours", 24)
        return f"""\
SELECT MAX({test.column}) AS latest_timestamp,
       CURRENT_TIMESTAMP AS check_time,
       EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - MAX({test.column}))) / 3600 AS age_hours
FROM {test.table}
HAVING EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - MAX({test.column}))) / 3600 > {max_hours};"""

    def _referential_query(self, test: DataQualityTest) -> str:
        """Build REFERENTIAL_INTEGRITY assertion query."""
        ref_table = test.parameters.get("reference_table", "")
        ref_column = test.parameters.get("reference_column", "")
        return f"""\
SELECT src.{test.column}, COUNT(*) AS orphan_count
FROM {test.table} src
LEFT JOIN {ref_table} ref ON src.{test.column} = ref.{ref_column}
WHERE ref.{ref_column} IS NULL
  AND src.{test.column} IS NOT NULL
GROUP BY src.{test.column}
LIMIT 100;"""

    def _custom_sql_query(self, test: DataQualityTest) -> str:
        """Build CUSTOM_SQL assertion query."""
        if test.sql_expression:
            return test.sql_expression
        return f"""\
-- Custom assertion - replace with actual condition
SELECT *
FROM {test.table}
WHERE 1=0  -- Replace with failure condition
LIMIT 100;"""

    def _fallback_query(self, test: DataQualityTest) -> str:
        """Build fallback assertion query."""
        col = test.column or "*"
        return f"""\
-- Fallback assertion for type: {test.assertion_type.value}
SELECT COUNT(*) AS check_count
FROM {test.table}
WHERE {col} IS NULL;"""
