/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ApiKeyResponseExpiresAt } from "./apiKeyResponseExpiresAt";
import type { ApiKeyResponseLastUsedAt } from "./apiKeyResponseLastUsedAt";

/**
 * Response for an API key (without revealing the key).
 */
export interface ApiKeyResponse {
  created_at: string;
  expires_at?: ApiKeyResponseExpiresAt;
  id: string;
  is_active: boolean;
  key_prefix: string;
  last_used_at?: ApiKeyResponseLastUsedAt;
  name: string;
  scopes: string[];
}
