/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ApprovalDecisionResponseComment } from "./approvalDecisionResponseComment";

/**
 * Response for an approval decision.
 */
export interface ApprovalDecisionResponse {
  comment?: ApprovalDecisionResponseComment;
  decided_at: string;
  decided_by: string;
  decision: string;
  id: string;
  investigation_id: string;
}
