/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ApprovalRequestResponseComment } from "./approvalRequestResponseComment";
import type { ApprovalRequestResponseContext } from "./approvalRequestResponseContext";
import type { ApprovalRequestResponseDatasetId } from "./approvalRequestResponseDatasetId";
import type { ApprovalRequestResponseDecidedAt } from "./approvalRequestResponseDecidedAt";
import type { ApprovalRequestResponseDecidedBy } from "./approvalRequestResponseDecidedBy";
import type { ApprovalRequestResponseDecision } from "./approvalRequestResponseDecision";
import type { ApprovalRequestResponseMetricName } from "./approvalRequestResponseMetricName";
import type { ApprovalRequestResponseModifications } from "./approvalRequestResponseModifications";
import type { ApprovalRequestResponseSeverity } from "./approvalRequestResponseSeverity";

/**
 * Response for an approval request.
 */
export interface ApprovalRequestResponse {
  comment?: ApprovalRequestResponseComment;
  context: ApprovalRequestResponseContext;
  dataset_id?: ApprovalRequestResponseDatasetId;
  decided_at?: ApprovalRequestResponseDecidedAt;
  decided_by?: ApprovalRequestResponseDecidedBy;
  decision?: ApprovalRequestResponseDecision;
  id: string;
  investigation_id: string;
  metric_name?: ApprovalRequestResponseMetricName;
  modifications?: ApprovalRequestResponseModifications;
  request_type: string;
  requested_at: string;
  requested_by: string;
  severity?: ApprovalRequestResponseSeverity;
}
