/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { BranchStateResponseEvidenceItem } from "./branchStateResponseEvidenceItem";
import type { MatchedPatternResponse } from "./matchedPatternResponse";
import type { BranchStateResponseParentBranchId } from "./branchStateResponseParentBranchId";
import type { StepHistoryItemResponse } from "./stepHistoryItemResponse";
import type { BranchStateResponseSynthesis } from "./branchStateResponseSynthesis";

/**
 * State of a branch for API responses.
 */
export interface BranchStateResponse {
  branch_id: string;
  can_merge?: boolean;
  current_step: string;
  evidence?: BranchStateResponseEvidenceItem[];
  matched_patterns?: MatchedPatternResponse[];
  parent_branch_id?: BranchStateResponseParentBranchId;
  status: string;
  step_history?: StepHistoryItemResponse[];
  synthesis?: BranchStateResponseSynthesis;
}
