/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { FeedbackCreateComment } from "./feedbackCreateComment";
import type { FeedbackCreateRating } from "./feedbackCreateRating";
import type { FeedbackCreateReason } from "./feedbackCreateReason";
import type { FeedbackCreateTargetType } from "./feedbackCreateTargetType";

/**
 * Request body for submitting feedback.
 */
export interface FeedbackCreate {
  comment?: FeedbackCreateComment;
  investigation_id: string;
  rating: FeedbackCreateRating;
  reason?: FeedbackCreateReason;
  target_id: string;
  target_type: FeedbackCreateTargetType;
}
