/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { JobRunResponse } from "./jobRunResponse";

/**
 * Response for job runs.
 */
export interface JobRunsResponse {
  runs: JobRunResponse[];
  total: number;
}
