/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ListDatasourceDatasetsApiV1V2DatasourcesDatasourceIdDatasetsGetParams =
  {
    table_type?: string | null;
    search?: string | null;
    limit?: number;
    offset?: number;
  };
