/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { OrgMemberResponseName } from "./orgMemberResponseName";

/**
 * Response for an org member.
 */
export interface OrgMemberResponse {
  created_at: string;
  email: string;
  name: OrgMemberResponseName;
  role: string;
  user_id: string;
}
