/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { RegisterRequestOrgSlug } from "./registerRequestOrgSlug";

/**
 * Registration request body.
 */
export interface RegisterRequest {
  email: string;
  name: string;
  org_name: string;
  org_slug?: RegisterRequestOrgSlug;
  password: string;
}
