/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SCIMUserUpdateRequestActive } from "./sCIMUserUpdateRequestActive";
import type { SCIMUserUpdateRequestDisplayName } from "./sCIMUserUpdateRequestDisplayName";
import type { SCIMUserUpdateRequestEmails } from "./sCIMUserUpdateRequestEmails";
import type { SCIMUserUpdateRequestName } from "./sCIMUserUpdateRequestName";
import type { SCIMUserUpdateRequestUserName } from "./sCIMUserUpdateRequestUserName";

/**
 * SCIM user update request.
 */
export interface SCIMUserUpdateRequest {
  active?: SCIMUserUpdateRequestActive;
  displayName?: SCIMUserUpdateRequestDisplayName;
  emails?: SCIMUserUpdateRequestEmails;
  name?: SCIMUserUpdateRequestName;
  schemas: string[];
  userName?: SCIMUserUpdateRequestUserName;
}
