/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SourceTypeResponseCapabilities } from "./sourceTypeResponseCapabilities";
import type { SourceTypeResponseConfigSchema } from "./sourceTypeResponseConfigSchema";

/**
 * Response for a source type definition.
 */
export interface SourceTypeResponse {
  capabilities: SourceTypeResponseCapabilities;
  category: string;
  config_schema: SourceTypeResponseConfigSchema;
  description: string;
  display_name: string;
  icon: string;
  type: string;
}
