/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SSODiscoverResponseAuthUrl } from "./sSODiscoverResponseAuthUrl";
import type { SSODiscoverResponseDisplayName } from "./sSODiscoverResponseDisplayName";
import type { SSODiscoverResponseState } from "./sSODiscoverResponseState";

/**
 * Response with SSO discovery result.
 */
export interface SSODiscoverResponse {
  auth_url?: SSODiscoverResponseAuthUrl;
  display_name?: SSODiscoverResponseDisplayName;
  method: string;
  state?: SSODiscoverResponseState;
}
