/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response with JWT tokens after SSO authentication.
 */
export interface SSOTokenResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
}
