/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response for schema sync.
 */
export interface SyncResponse {
  datasets_removed: number;
  datasets_synced: number;
  message: string;
}
