/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { UpdateTenantSettingsRequestLineageProviders } from "./updateTenantSettingsRequestLineageProviders";
import type { UpdateTenantSettingsRequestMaxQueriesPerInvestigation } from "./updateTenantSettingsRequestMaxQueriesPerInvestigation";
import type { UpdateTenantSettingsRequestName } from "./updateTenantSettingsRequestName";
import type { UpdateTenantSettingsRequestNotificationEmail } from "./updateTenantSettingsRequestNotificationEmail";
import type { UpdateTenantSettingsRequestRequireApprovalForQueries } from "./updateTenantSettingsRequestRequireApprovalForQueries";
import type { UpdateTenantSettingsRequestSlackChannel } from "./updateTenantSettingsRequestSlackChannel";

/**
 * Request to update tenant settings.
 */
export interface UpdateTenantSettingsRequest {
  /** Lineage providers configuration */
  lineage_providers?: UpdateTenantSettingsRequestLineageProviders;
  max_queries_per_investigation?: UpdateTenantSettingsRequestMaxQueriesPerInvestigation;
  name?: UpdateTenantSettingsRequestName;
  notification_email?: UpdateTenantSettingsRequestNotificationEmail;
  require_approval_for_queries?: UpdateTenantSettingsRequestRequireApprovalForQueries;
  slack_channel?: UpdateTenantSettingsRequestSlackChannel;
}
