/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { VoteCreateVote } from "./voteCreateVote";

/**
 * Request body for voting.
 */
export interface VoteCreate {
  /** 1 for upvote, -1 for downvote */
  vote: VoteCreateVote;
}
