/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Activation funnel statistics response.
 */
export interface ActivationFunnelResponse {
  activation_rate: number;
  investigation_rate: number;
  issue_rate: number;
  tenants_activated: number;
  tenants_with_investigation: number;
  tenants_with_issue: number;
  total_tenants: number;
}
