/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ActivationStatusResponseActivatedAt } from "./activationStatusResponseActivatedAt";
import type { ActivationStatusResponseDaysToActivation } from "./activationStatusResponseDaysToActivation";
import type { ActivationStatusResponseFirstInvestigationAt } from "./activationStatusResponseFirstInvestigationAt";
import type { ActivationStatusResponseFirstIssueAt } from "./activationStatusResponseFirstIssueAt";

/**
 * Activation status response.
 */
export interface ActivationStatusResponse {
  activated_at: ActivationStatusResponseActivatedAt;
  created_at: string;
  days_to_activation: ActivationStatusResponseDaysToActivation;
  first_investigation_at: ActivationStatusResponseFirstInvestigationAt;
  first_issue_at: ActivationStatusResponseFirstIssueAt;
  is_activated: boolean;
  tenant_id: string;
}
