/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AmbiguousAssetError } from "./ambiguousAssetError";

/**
 * Response when one or more assets are ambiguous.
 */
export interface AmbiguousAssetsResponse {
  ambiguous_assets: AmbiguousAssetError[];
  detail?: string;
}
