/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AssetRefRequestOutput } from "./assetRefRequestOutput";
import type { AmbiguousAssetCandidate } from "./ambiguousAssetCandidate";

/**
 * Error response for ambiguous asset.
 */
export interface AmbiguousAssetError {
  asset: AssetRefRequestOutput;
  candidates: AmbiguousAssetCandidate[];
  hint: string;
  message: string;
}
