/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AmbiguousAssetCandidateConnectionInfo } from "./ambiguousAssetCandidateConnectionInfo";

/**
 * Candidate when asset is ambiguous.
 */
export interface AmbiguousAssetCandidate {
  connection_info?: AmbiguousAssetCandidateConnectionInfo;
  datasource_id: string;
  datasource_name: string;
  platform: string;
}
