/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Summary of detected anomaly.
 */
export interface AnomalySummary {
  anomaly_id: string;
  anomaly_type: string;
  dataset_id: string;
  detected_at: string;
  severity: string;
}
