/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ApiKeyCreatedResponseExpiresAt } from "./apiKeyCreatedResponseExpiresAt";

/**
 * Response after creating an API key with the key value.
 */
export interface ApiKeyCreatedResponse {
  expires_at?: ApiKeyCreatedResponseExpiresAt;
  id: string;
  key: string;
  key_prefix: string;
  name: string;
  scopes: string[];
}
