/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AssetInstanceResultSchemaName } from "./assetInstanceResultSchemaName";

/**
 * Single asset instance in search results.
 */
export interface AssetInstanceResult {
  /** Fully qualified URN: urn:dataing:{platform}:{datasource_id}:{native_path} */
  asset_urn: string;
  /** Datasource ID */
  datasource_id: string;
  /** Human-readable datasource name */
  datasource_name: string;
  /** Human-readable table/view name */
  display_name: string;
  /** Why this result matched: name_prefix, path_match, fuzzy */
  match_reason: string;
  /** Database platform type (postgres, snowflake, etc.) */
  platform: string;
  /** Database schema name */
  schema_name?: AssetInstanceResultSchemaName;
  /** Asset type: table, view, materialized_view */
  type: string;
}
