/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Approximate total matching results (may be expensive to compute exactly)
 */
export type AssetInstanceSearchResponseTotalHint = number | null;
