/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AssetRefRequestDatasourceId } from "./assetRefRequestDatasourceId";

/**
 * Asset reference in request.
 */
export interface AssetRefRequest {
  datasource_id?: AssetRefRequestDatasourceId;
  name: string;
  platform: string;
}
