/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AssetInstanceResult } from "./assetInstanceResult";
import type { AssetInstanceSearchResponseNextCursor } from "./assetInstanceSearchResponseNextCursor";
import type { AssetInstanceSearchResponseTotalHint } from "./assetInstanceSearchResponseTotalHint";

/**
 * Response from asset instances search endpoint.
 */
export interface AssetInstanceSearchResponse {
  /** Opaque cursor for fetching next page, null if no more results */
  next_cursor?: AssetInstanceSearchResponseNextCursor;
  results: AssetInstanceResult[];
  /** Approximate total matching results (may be expensive to compute exactly) */
  total_hint?: AssetInstanceSearchResponseTotalHint;
}
