/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Opaque cursor for fetching next page, null if no more results
 */
export type AssetInstanceSearchResponseNextCursor = string | null;
