/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AssetRefRequestOutputDatasourceId } from "./assetRefRequestOutputDatasourceId";

/**
 * Asset reference in request.
 */
export interface AssetRefRequestOutput {
  /** Optional datasource ID for disambiguation */
  datasource_id?: AssetRefRequestOutputDatasourceId;
  /** Fully qualified name (db.schema.table) */
  name: string;
  /** Data platform (postgres, snowflake, dbt) */
  platform: string;
}
