/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { BriefScopeDatasourceId } from "./briefScopeDatasourceId";
import type { BriefScopeTimeWindow } from "./briefScopeTimeWindow";

/**
 * Where the investigation should look.
 */
export interface BriefScope {
  datasource_id?: BriefScopeDatasourceId;
  /** @maxItems 20 */
  tables?: string[];
  time_window?: BriefScopeTimeWindow;
}
