/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { BriefClaimMessageId } from "./briefClaimMessageId";
import type { BriefClaimQueryResultId } from "./briefClaimQueryResultId";

/**
 * A finding or exclusion, optionally backed by a thread message and a query.
 */
export interface BriefClaim {
  message_id?: BriefClaimMessageId;
  query_result_id?: BriefClaimQueryResultId;
  /**
   * @minLength 1
   * @maxLength 500
   */
  statement: string;
}
