/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { BulkRepoMappingItemBranch } from "./bulkRepoMappingItemBranch";
import type { BulkRepoMappingItemFilePath } from "./bulkRepoMappingItemFilePath";
import type { BulkRepoMappingItemJobName } from "./bulkRepoMappingItemJobName";

/**
 * Single item in a bulk import request.
 */
export interface BulkRepoMappingItem {
  branch?: BulkRepoMappingItemBranch;
  /**
   * @minLength 1
   * @maxLength 500
   */
  dataset_pattern: string;
  file_path?: BulkRepoMappingItemFilePath;
  job_name?: BulkRepoMappingItemJobName;
  /** @pattern ^(exact|glob)$ */
  pattern_type?: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  repo_name: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  repo_owner: string;
}
