/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { BulkRepoMappingItem } from "./bulkRepoMappingItem";

/**
 * Request to bulk import dataset-to-repository mappings.
 */
export interface BulkImportRequest {
  /**
   * @minItems 1
   * @maxItems 1000
   */
  mappings: BulkRepoMappingItem[];
}
