/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { BundleLineageGraphResponseDatasets } from "./bundleLineageGraphResponseDatasets";
import type { LineageEdge } from "./lineageEdge";
import type { BundleLineageGraphResponseRoot } from "./bundleLineageGraphResponseRoot";

/**
 * Lineage graph response.
 */
export interface BundleLineageGraphResponse {
  datasets?: BundleLineageGraphResponseDatasets;
  edges?: LineageEdge[];
  root?: BundleLineageGraphResponseRoot;
}
