/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response for cancelling an investigation.
 */
export interface CancelInvestigationResponse {
  investigation_id: string;
  jobs_cancelled?: number;
  status: string;
}
