/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ChainVerificationResponseError } from "./chainVerificationResponseError";
import type { ChainVerificationResponseFirstBrokenSeq } from "./chainVerificationResponseFirstBrokenSeq";
import type { ChainVerificationResponseRootHash } from "./chainVerificationResponseRootHash";
import type { ChainVerificationResponseRootHashMatches } from "./chainVerificationResponseRootHashMatches";

/**
 * Response from evidence chain verification.
 */
export interface ChainVerificationResponse {
  chain_available?: boolean;
  error?: ChainVerificationResponseError;
  evidence_count: number;
  first_broken_seq?: ChainVerificationResponseFirstBrokenSeq;
  investigation_id: string;
  is_valid: boolean;
  root_hash?: ChainVerificationResponseRootHash;
  root_hash_matches?: ChainVerificationResponseRootHashMatches;
}
