/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CodeChangeResponse } from "./codeChangeResponse";

/**
 * Response for a list of code changes.
 */
export interface CodeChangeListResponse {
  items: CodeChangeResponse[];
  total: number;
}
