/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CodeChangeResponseAffectedAssetsItem } from "./codeChangeResponseAffectedAssetsItem";
import type { CodeChangeResponseAuthorEmail } from "./codeChangeResponseAuthorEmail";
import type { CodeChangeResponseAuthorName } from "./codeChangeResponseAuthorName";
import type { CodeChangeResponseCommittedAt } from "./codeChangeResponseCommittedAt";
import type { CodeChangeResponseFilesChanged } from "./codeChangeResponseFilesChanged";
import type { CodeChangeResponseMessage } from "./codeChangeResponseMessage";

/**
 * Response for a code change (commit).
 */
export interface CodeChangeResponse {
  affected_assets: CodeChangeResponseAffectedAssetsItem[];
  author_email: CodeChangeResponseAuthorEmail;
  author_name: CodeChangeResponseAuthorName;
  commit_hash: string;
  committed_at: CodeChangeResponseCommittedAt;
  created_at: string;
  files_changed: CodeChangeResponseFilesChanged;
  id: string;
  message: CodeChangeResponseMessage;
  repo_id: string;
}
