/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CodifyTestResponseColumn } from "./codifyTestResponseColumn";

/**
 * A single test extracted from the investigation.
 */
export interface CodifyTestResponse {
  column?: CodifyTestResponseColumn;
  description: string;
  table: string;
  test_type: string;
}
