/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CodifyTestResponse } from "./codifyTestResponse";

/**
 * Response for codifying an investigation.
 */
export interface CodifyResponse {
  confidence: number;
  content: string;
  format: string;
  investigation_id: string;
  tests: CodifyTestResponse[];
}
