/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Output format for test generation.
 */
export type CodifyFormat = (typeof CodifyFormat)[keyof typeof CodifyFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CodifyFormat = {
  gx: "gx",
  dbt: "dbt",
  soda: "soda",
  sql: "sql",
} as const;
