/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ConfigFieldType =
  (typeof ConfigFieldType)[keyof typeof ConfigFieldType];

export const ConfigFieldType = {
  string: "string",
  integer: "integer",
  boolean: "boolean",
  enum: "enum",
  secret: "secret",
  file: "file",
  json: "json",
} as const;
