/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { FieldGroup } from "./fieldGroup";
import type { ConfigField } from "./configField";

/**
 * Configuration schema for an adapter.
 */
export interface ConfigSchema {
  field_groups: FieldGroup[];
  fields: ConfigField[];
}
