/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * One choice of an enum configuration field.
 */
export interface ConfigFieldOption {
  label: string;
  value: string;
}
