/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ConfigFieldDefaultValue } from "./configFieldDefaultValue";
import type { ConfigFieldDescription } from "./configFieldDescription";
import type { ConfigFieldHelpUrl } from "./configFieldHelpUrl";
import type { ConfigFieldMaxValue } from "./configFieldMaxValue";
import type { ConfigFieldMinValue } from "./configFieldMinValue";
import type { ConfigFieldOptions } from "./configFieldOptions";
import type { ConfigFieldPattern } from "./configFieldPattern";
import type { ConfigFieldPlaceholder } from "./configFieldPlaceholder";
import type { ConfigFieldShowIf } from "./configFieldShowIf";
import type { ConfigFieldType } from "./configFieldType";

/**
 * Configuration field for connection forms.
 */
export interface ConfigField {
  default_value?: ConfigFieldDefaultValue;
  description?: ConfigFieldDescription;
  group: string;
  help_url?: ConfigFieldHelpUrl;
  label: string;
  max_value?: ConfigFieldMaxValue;
  min_value?: ConfigFieldMinValue;
  name: string;
  options?: ConfigFieldOptions;
  pattern?: ConfigFieldPattern;
  placeholder?: ConfigFieldPlaceholder;
  required: boolean;
  show_if?: ConfigFieldShowIf;
  type: ConfigFieldType;
}
