/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ConnectGitRepoRequestAccessToken } from "./connectGitRepoRequestAccessToken";
import type { ConnectGitRepoRequestTrackedPaths } from "./connectGitRepoRequestTrackedPaths";

/**
 * Request to connect a git repository.
 */
export interface ConnectGitRepoRequest {
  access_token?: ConnectGitRepoRequestAccessToken;
  default_branch?: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** @pattern ^(github|gitlab|bitbucket)$ */
  provider: string;
  tracked_paths?: ConnectGitRepoRequestTrackedPaths;
  /**
   * @minLength 1
   * @maxLength 500
   */
  url: string;
}
