/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ContextBundleResponseAnomalies } from "./contextBundleResponseAnomalies";
import type { ContextBundleResponseDefaultDatasourceId } from "./contextBundleResponseDefaultDatasourceId";
import type { ContextBundleResponseLineage } from "./contextBundleResponseLineage";
import type { ContextBundleResponseOperational } from "./contextBundleResponseOperational";
import type { ResolvedAssetResponse } from "./resolvedAssetResponse";

/**
 * Context bundle response.
 */
export interface ContextBundleResponse {
  anomalies?: ContextBundleResponseAnomalies;
  /** Server-derived cache key */
  bundle_hash: string;
  bundle_id: string;
  default_datasource_id?: ContextBundleResponseDefaultDatasourceId;
  expires_at: string;
  lineage?: ContextBundleResponseLineage;
  operational?: ContextBundleResponseOperational;
  resolved_assets: ResolvedAssetResponse[];
}
