/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { OperationalFactsResponse } from "./operationalFactsResponse";

export type ContextBundleResponseOperational = OperationalFactsResponse | null;
