/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CreateSessionRequestMetadata } from "./createSessionRequestMetadata";
import type { CreateSessionRequestParentInvestigationId } from "./createSessionRequestParentInvestigationId";
import type { CreateSessionRequestTitle } from "./createSessionRequestTitle";

/**
 * Request to create a new assistant session.
 */
export interface CreateSessionRequest {
  metadata?: CreateSessionRequestMetadata;
  /** Optional parent investigation to link to */
  parent_investigation_id?: CreateSessionRequestParentInvestigationId;
  /** Optional session title */
  title?: CreateSessionRequestTitle;
}
