/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CreateDataSourceRequestConfig } from "./createDataSourceRequestConfig";

/**
 * Request to create a new data source.
 */
export interface CreateDataSourceRequest {
  /** Configuration for the adapter */
  config: CreateDataSourceRequestConfig;
  is_default?: boolean;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** Source type (e.g., 'postgresql', 'mongodb') */
  type: string;
}
