/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response from creating a session.
 */
export interface CreateSessionResponse {
  created_at: string;
  investigation_id: string;
  session_id: string;
}
