/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Time window for context (e.g., '7d', '24h')
 */
export type CreateBundleRequestWindow = string | null;
