/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DataingEntrypointsApiRoutesBundlesAssetRefRequest } from "./dataingEntrypointsApiRoutesBundlesAssetRefRequest";
import type { CreateBundleRequestWindow } from "./createBundleRequestWindow";

/**
 * Request to create a context bundle.
 */
export interface CreateBundleRequest {
  /**
   * Assets to include in bundle
   * @minItems 1
   */
  assets: DataingEntrypointsApiRoutesBundlesAssetRefRequest[];
  /** Include anomaly summary */
  include_anomalies?: boolean;
  /** Include lineage graph */
  include_lineage?: boolean;
  /** Include operational facts */
  include_operational?: boolean;
  /** Time window for context (e.g., '7d', '24h') */
  window?: CreateBundleRequestWindow;
}
