/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Optional parent investigation to link to
 */
export type CreateSessionRequestParentInvestigationId = string | null;
