/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CreateRunRequestBundle } from "./createRunRequestBundle";
import type { CreateRunRequestBundleId } from "./createRunRequestBundleId";

/**
 * Request to create a run.

Accepts exactly one of bundle_id or bundle (inline).
 */
export interface CreateRunRequest {
  /** Inline bundle specification */
  bundle?: CreateRunRequestBundle;
  /** Existing bundle ID to use */
  bundle_id?: CreateRunRequestBundleId;
  /** Investigation goal/question */
  goal: string;
}
