/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CreateUserRequestName } from "./createUserRequestName";
import type { CreateUserRequestRole } from "./createUserRequestRole";

/**
 * Request to create a user.
 */
export interface CreateUserRequest {
  email: string;
  name?: CreateUserRequestName;
  role?: CreateUserRequestRole;
}
