/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CreateRepoMappingRequestMetadataAnyOf } from "./createRepoMappingRequestMetadataAnyOf";

export type CreateRepoMappingRequestMetadata =
  CreateRepoMappingRequestMetadataAnyOf | null;
