/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Request to create a webhook.
 */
export interface CreateWebhookRequest {
  /** @minItems 1 */
  events: string[];
  /**
   * @minLength 1
   * @maxLength 2083
   */
  url: string;
}
