/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CreateRepoMappingRequestBranch } from "./createRepoMappingRequestBranch";
import type { CreateRepoMappingRequestFilePath } from "./createRepoMappingRequestFilePath";
import type { CreateRepoMappingRequestJobName } from "./createRepoMappingRequestJobName";
import type { CreateRepoMappingRequestMetadata } from "./createRepoMappingRequestMetadata";

/**
 * Request to create a dataset-to-repository mapping.
 */
export interface CreateRepoMappingRequest {
  branch?: CreateRepoMappingRequestBranch;
  /**
   * @minLength 1
   * @maxLength 500
   */
  dataset_pattern: string;
  file_path?: CreateRepoMappingRequestFilePath;
  job_name?: CreateRepoMappingRequestJobName;
  metadata?: CreateRepoMappingRequestMetadata;
  /** @pattern ^(exact|glob)$ */
  pattern_type?: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  repo_name: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  repo_owner: string;
}
