/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CredentialsStatusResponseCreatedAt } from "./credentialsStatusResponseCreatedAt";
import type { CredentialsStatusResponseDbUsername } from "./credentialsStatusResponseDbUsername";
import type { CredentialsStatusResponseLastUsedAt } from "./credentialsStatusResponseLastUsedAt";

/**
 * Response for credentials status check.
 */
export interface CredentialsStatusResponse {
  configured: boolean;
  created_at?: CredentialsStatusResponseCreatedAt;
  db_username?: CredentialsStatusResponseDbUsername;
  last_used_at?: CredentialsStatusResponseLastUsedAt;
}
