/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { CredentialsTestResponseError } from "./credentialsTestResponseError";
import type { CredentialsTestResponseTablesAccessible } from "./credentialsTestResponseTablesAccessible";

/**
 * Response for testing credentials.
 */
export interface CredentialsTestResponse {
  error?: CredentialsTestResponseError;
  success: boolean;
  tables_accessible?: CredentialsTestResponseTablesAccessible;
}
