/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DashboardStats } from "./dashboardStats";
import type { RecentInvestigation } from "./recentInvestigation";

/**
 * Full dashboard response.
 */
export interface DashboardResponse {
  recent_investigations: RecentInvestigation[];
  stats: DashboardStats;
}
