/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { RecentInvestigation } from "./recentInvestigation";
import type { DashboardStats } from "./dashboardStats";

/**
 * Full dashboard response.
 */
export interface DashboardResponse {
  recent_investigations: RecentInvestigation[];
  stats: DashboardStats;
}
