/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Dashboard statistics.
 */
export interface DashboardStats {
  active_investigations: number;
  completed_today: number;
  data_sources: number;
}
