/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Optional datasource ID for disambiguation
 */
export type DataingEntrypointsApiRoutesBundlesAssetRefRequestDatasourceId =
  | string
  | null;
