/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DatasetDetailResponseCatalogName } from "./datasetDetailResponseCatalogName";
import type { DatasetDetailResponseColumnCount } from "./datasetDetailResponseColumnCount";
import type { DatasetDetailResponseColumnsItem } from "./datasetDetailResponseColumnsItem";
import type { DatasetDetailResponseDatasourceName } from "./datasetDetailResponseDatasourceName";
import type { DatasetDetailResponseDatasourceType } from "./datasetDetailResponseDatasourceType";
import type { DatasetDetailResponseLastSyncedAt } from "./datasetDetailResponseLastSyncedAt";
import type { DatasetDetailResponseRowCount } from "./datasetDetailResponseRowCount";
import type { DatasetDetailResponseSchemaName } from "./datasetDetailResponseSchemaName";

/**
 * Detailed dataset response with columns.
 */
export interface DatasetDetailResponse {
  catalog_name?: DatasetDetailResponseCatalogName;
  column_count?: DatasetDetailResponseColumnCount;
  columns?: DatasetDetailResponseColumnsItem[];
  created_at: string;
  datasource_id: string;
  datasource_name?: DatasetDetailResponseDatasourceName;
  datasource_type?: DatasetDetailResponseDatasourceType;
  id: string;
  last_synced_at?: DatasetDetailResponseLastSyncedAt;
  name: string;
  native_path: string;
  row_count?: DatasetDetailResponseRowCount;
  schema_name?: DatasetDetailResponseSchemaName;
  table_type: string;
}
