/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DatasetRepoResponseAllMatches } from "./datasetRepoResponseAllMatches";
import type { DatasetRepoResponsePrimary } from "./datasetRepoResponsePrimary";

/**
 * Response for resolving a dataset's repository.
 */
export interface DatasetRepoResponse {
  all_matches?: DatasetRepoResponseAllMatches;
  dataset_id: string;
  primary?: DatasetRepoResponsePrimary;
}
