/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DataingEntrypointsApiRoutesCredentialsTestConnectionResponseError } from "./dataingEntrypointsApiRoutesCredentialsTestConnectionResponseError";
import type { DataingEntrypointsApiRoutesCredentialsTestConnectionResponseTablesAccessible } from "./dataingEntrypointsApiRoutesCredentialsTestConnectionResponseTablesAccessible";

/**
 * Response for testing credentials.
 */
export interface DataingEntrypointsApiRoutesCredentialsTestConnectionResponse {
  error?: DataingEntrypointsApiRoutesCredentialsTestConnectionResponseError;
  success: boolean;
  tables_accessible?: DataingEntrypointsApiRoutesCredentialsTestConnectionResponseTablesAccessible;
}
