/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DataingEntrypointsApiRoutesRunsAssetRefRequestDatasourceId } from "./dataingEntrypointsApiRoutesRunsAssetRefRequestDatasourceId";

/**
 * Asset reference in request.
 */
export interface DataingEntrypointsApiRoutesRunsAssetRefRequest {
  datasource_id?: DataingEntrypointsApiRoutesRunsAssetRefRequestDatasourceId;
  name: string;
  platform: string;
}
