/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DataingEntrypointsApiRoutesBundlesLineageGraphResponseDatasets } from "./dataingEntrypointsApiRoutesBundlesLineageGraphResponseDatasets";
import type { LineageEdge } from "./lineageEdge";
import type { DataingEntrypointsApiRoutesBundlesLineageGraphResponseRoot } from "./dataingEntrypointsApiRoutesBundlesLineageGraphResponseRoot";

/**
 * Lineage graph response.
 */
export interface DataingEntrypointsApiRoutesBundlesLineageGraphResponse {
  datasets?: DataingEntrypointsApiRoutesBundlesLineageGraphResponseDatasets;
  edges?: LineageEdge[];
  root?: DataingEntrypointsApiRoutesBundlesLineageGraphResponseRoot;
}
