/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DataSourceResponse } from "./dataSourceResponse";

/**
 * Response for listing data sources.
 */
export interface DataSourceListResponse {
  items: DataSourceResponse[];
  total: number;
}
