/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DataingEntrypointsApiRoutesLineageLineageGraphResponseDatasets } from "./dataingEntrypointsApiRoutesLineageLineageGraphResponseDatasets";
import type { LineageEdgeResponse } from "./lineageEdgeResponse";
import type { DataingEntrypointsApiRoutesLineageLineageGraphResponseJobs } from "./dataingEntrypointsApiRoutesLineageLineageGraphResponseJobs";

/**
 * Response for a lineage graph.
 */
export interface DataingEntrypointsApiRoutesLineageLineageGraphResponse {
  datasets: DataingEntrypointsApiRoutesLineageLineageGraphResponseDatasets;
  edges: LineageEdgeResponse[];
  jobs: DataingEntrypointsApiRoutesLineageLineageGraphResponseJobs;
  root: string;
}
