/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { InvestigationSummary } from "./investigationSummary";

/**
 * Response for dataset investigations.
 */
export interface DatasetInvestigationsResponse {
  investigations: InvestigationSummary[];
  total: number;
}
