/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Request to send a message.
 */
export interface DataingEntrypointsApiRoutesAssistantSendMessageRequest {
  /**
   * @minLength 1
   * @maxLength 32000
   */
  content: string;
}
