/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Request body for sending a message.
 */
export interface DataingEntrypointsApiRoutesInvestigationsSendMessageRequest {
  message: string;
}
