/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DataingEntrypointsApiRoutesDatasourcesTestConnectionResponseLatencyMs } from "./dataingEntrypointsApiRoutesDatasourcesTestConnectionResponseLatencyMs";
import type { DataingEntrypointsApiRoutesDatasourcesTestConnectionResponseServerVersion } from "./dataingEntrypointsApiRoutesDatasourcesTestConnectionResponseServerVersion";

/**
 * Response for testing a connection.
 */
export interface DataingEntrypointsApiRoutesDatasourcesTestConnectionResponse {
  latency_ms?: DataingEntrypointsApiRoutesDatasourcesTestConnectionResponseLatencyMs;
  message: string;
  server_version?: DataingEntrypointsApiRoutesDatasourcesTestConnectionResponseServerVersion;
  success: boolean;
}
