/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DiffResponseCurrentValue } from "./diffResponseCurrentValue";
import type { DiffResponseDelta } from "./diffResponseDelta";
import type { DiffResponseDeltaPercent } from "./diffResponseDeltaPercent";
import type { DiffResponsePreviousValue } from "./diffResponsePreviousValue";
import type { DiffResponseTrend } from "./diffResponseTrend";
import type { DiffSample } from "./diffSample";

/**
 * Response for metric diff.
 */
export interface DiffResponse {
  current_value?: DiffResponseCurrentValue;
  delta?: DiffResponseDelta;
  delta_percent?: DiffResponseDeltaPercent;
  metric: string;
  previous_value?: DiffResponsePreviousValue;
  samples?: DiffSample[];
  /** up, down, stable, or unknown */
  trend?: DiffResponseTrend;
  window: string;
}
