/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Time-series sample for diff.
 */
export interface DiffSample {
  timestamp: string;
  value: number;
}
