/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DiffRequestDatasourceId } from "./diffRequestDatasourceId";

/**
 * Request to compute metric diff.
 */
export interface DiffRequest {
  /** Bundle ID to analyze */
  bundle_id: string;
  /** Optional datasource override */
  datasource_id?: DiffRequestDatasourceId;
  /** Metric to compare (e.g., row_count, null_rate) */
  metric: string;
  /** Time window for comparison (e.g., 7d, 24h) */
  window?: string;
}
