/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { EvidenceResponsePrevHash } from "./evidenceResponsePrevHash";

/**
 * Response for stored evidence.
 */
export interface EvidenceResponse {
  content_hash: string;
  created_at: string;
  id: string;
  kind: string;
  prev_hash?: EvidenceResponsePrevHash;
  run_id: string;
  seq: number;
}
