/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response for explanation.
 */
export interface ExplainResponse {
  insights?: string[];
  recommendations?: string[];
  related_assets?: string[];
  /** Natural language explanation */
  summary: string;
}
