/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ExplainRequestFocus } from "./explainRequestFocus";

/**
 * Request for AI-powered explanation.
 */
export interface ExplainRequest {
  /** Bundle ID to explain */
  bundle_id: string;
  /** Focus area (anomalies, lineage, data_quality) */
  focus?: ExplainRequestFocus;
}
