/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { FieldGroupDescription } from "./fieldGroupDescription";

/**
 * Group of configuration fields.
 */
export interface FieldGroup {
  collapsed_by_default?: boolean;
  description?: FieldGroupDescription;
  id: string;
  label: string;
}
