/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type GetActivationFunnelApiV1AnalyticsActivationFunnelGetParams = {
  /**
   * Look back period in days
   * @minimum 1
   * @maximum 365
   */
  days?: number;
};
