/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type GetColumnLineageApiV1LineageColumnLineageGetParams = {
  /**
   * Dataset identifier (platform://name)
   */
  dataset: string;
  /**
   * Column name to trace
   */
  column: string;
};
