/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SLAPolicyResponse } from "./sLAPolicyResponse";

export type GetDefaultSlaPolicyApiV1SlaPoliciesDefaultGet200 =
  SLAPolicyResponse | null;
