/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type GetDatasourceSchemaApiV1V2DatasourcesDatasourceIdSchemaGetParams = {
  table_pattern?: string | null;
  include_views?: boolean;
  max_tables?: number;
};
