/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type GetDownstreamApiV1LineageDownstreamGetParams = {
  /**
   * Dataset identifier (platform://name)
   */
  dataset: string;
  /**
   * Depth of lineage traversal
   * @minimum 1
   * @maximum 10
   */
  depth?: number;
};
