/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type GetJobRunsApiV1LineageJobJobIdRunsGetParams = {
  /**
   * Maximum runs to return
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
