/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type GetLineageGraphApiV1LineageGraphGetParams = {
  /**
   * Dataset identifier (platform://name)
   */
  dataset: string;
  /**
   * Upstream traversal depth
   */
  upstream_depth?: number;
  /**
   * Downstream traversal depth
   */
  downstream_depth?: number;
};
