/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type GetWeeklyUsageApiV1AnalyticsWeeklyUsageGetParams = {
  /**
   * Number of weeks to return
   * @minimum 1
   * @maximum 52
   */
  weeks?: number;
  /**
   * Filter by team ID
   */
  team_id?: string | null;
};
