/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { GitRepoResponseLastSyncAt } from "./gitRepoResponseLastSyncAt";
import type { GitRepoResponseSyncError } from "./gitRepoResponseSyncError";
import type { GitRepoResponseTrackedPaths } from "./gitRepoResponseTrackedPaths";
import type { GitRepoResponseUpdatedAt } from "./gitRepoResponseUpdatedAt";

/**
 * Response for a git repository.
 */
export interface GitRepoResponse {
  created_at: string;
  default_branch: string;
  id: string;
  last_sync_at: GitRepoResponseLastSyncAt;
  name: string;
  provider: string;
  sync_error: GitRepoResponseSyncError;
  sync_status: string;
  tracked_paths: GitRepoResponseTrackedPaths;
  updated_at: GitRepoResponseUpdatedAt;
  url: string;
}
