/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ImportDbtManifestApiV1DatasetRepoMappingsImportDbtManifestPostParams =
  {
    /**
     * @minLength 1
     */
    repo_owner: string;
    /**
     * @minLength 1
     */
    repo_name: string;
    branch?: string | null;
  };
