/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response for importing a snapshot archive.
 */
export interface ImportSnapshotResponse {
  evidence_count: number;
  investigation_id: string;
  is_replay?: boolean;
  original_investigation_id: string;
  status?: string;
}
