/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { DataingEntrypointsApiRoutesRunsAssetRefRequest } from "./dataingEntrypointsApiRoutesRunsAssetRefRequest";
import type { InlineBundleRequestWindow } from "./inlineBundleRequestWindow";

/**
 * Inline bundle specification for one-call API.
 */
export interface InlineBundleRequest {
  assets: DataingEntrypointsApiRoutesRunsAssetRefRequest[];
  window?: InlineBundleRequestWindow;
}
