/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { BriefClaim } from "./briefClaim";
import type { BriefScope } from "./briefScope";

/**
 * Everything the thread learned that the manager should start from.
 */
export interface InvestigationBrief {
  /** @maxItems 20 */
  findings?: BriefClaim[];
  /** @maxItems 10 */
  leads?: string[];
  /** @maxLength 2000 */
  notes?: string;
  /** @maxItems 20 */
  ruled_out?: BriefClaim[];
  scope?: BriefScope;
  /**
   * @minLength 1
   * @maxLength 1000
   */
  symptom: string;
  version?: 1;
}
