/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { InvestigationStatusResponseError } from "./investigationStatusResponseError";
import type { InvestigationStatusResponseEventsItem } from "./investigationStatusResponseEventsItem";
import type { InvestigationStatusResponseFinding } from "./investigationStatusResponseFinding";

/**
 * Response for investigation status.
 */
export interface InvestigationStatusResponse {
  error?: InvestigationStatusResponseError;
  events: InvestigationStatusResponseEventsItem[];
  finding?: InvestigationStatusResponseFinding;
  investigation_id: string;
  status: string;
}
