/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { InvestigationSummarySeverity } from "./investigationSummarySeverity";

/**
 * Summary of an investigation for dataset detail.
 */
export interface InvestigationSummary {
  created_at: string;
  id: string;
  metric_name: string;
  severity?: InvestigationSummarySeverity;
  status: string;
}
