/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { InvestigationRunResponse } from "./investigationRunResponse";

/**
 * Paginated investigation run list response.
 */
export interface InvestigationRunListResponse {
  items: InvestigationRunResponse[];
  total: number;
}
