/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Investigation list item for API responses.
 */
export interface InvestigationListItem {
  created_at: string;
  dataset_id: string;
  investigation_id: string;
  status: string;
}
