/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { InvestigationRunCreateDatasetId } from "./investigationRunCreateDatasetId";

/**
 * Request body for spawning an investigation from an issue.
 */
export interface InvestigationRunCreate {
  dataset_id?: InvestigationRunCreateDatasetId;
  /** @pattern ^(safe|standard|deep)$ */
  execution_profile?: string;
  /** @minLength 1 */
  focus_prompt: string;
}
