/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { InvestigationRunResponseApprovalStatus } from "./investigationRunResponseApprovalStatus";
import type { InvestigationRunResponseCompletedAt } from "./investigationRunResponseCompletedAt";
import type { InvestigationRunResponseConfidence } from "./investigationRunResponseConfidence";
import type { InvestigationRunResponseFocusPrompt } from "./investigationRunResponseFocusPrompt";
import type { InvestigationRunResponseRootCauseTag } from "./investigationRunResponseRootCauseTag";
import type { InvestigationRunResponseSynthesisSummary } from "./investigationRunResponseSynthesisSummary";

/**
 * Response for an investigation run.
 */
export interface InvestigationRunResponse {
  approval_status: InvestigationRunResponseApprovalStatus;
  completed_at: InvestigationRunResponseCompletedAt;
  confidence: InvestigationRunResponseConfidence;
  created_at: string;
  execution_profile: string;
  focus_prompt: InvestigationRunResponseFocusPrompt;
  id: string;
  investigation_id: string;
  issue_id: string;
  root_cause_tag: InvestigationRunResponseRootCauseTag;
  synthesis_summary: InvestigationRunResponseSynthesisSummary;
  trigger_type: string;
}
