/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { BranchStateResponse } from "./branchStateResponse";
import type { InvestigationStateResponseUserBranch } from "./investigationStateResponseUserBranch";

/**
 * Full investigation state for API responses.
 */
export interface InvestigationStateResponse {
  investigation_id: string;
  main_branch: BranchStateResponse;
  status: string;
  user_branch?: InvestigationStateResponseUserBranch;
}
