/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * For allowed moves whose guard the issue does not yet satisfy, the fields to send in the same PATCH (assignee_user_id or resolution_note)
 */
export type IssueResponseTransitionRequirements = { [key: string]: string[] };
