/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { IssueCommentResponse } from "./issueCommentResponse";

/**
 * Paginated comment list response.
 */
export interface IssueCommentListResponse {
  items: IssueCommentResponse[];
  total: number;
}
