/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { IssueResponseAcknowledgedBy } from "./issueResponseAcknowledgedBy";
import type { IssueResponseAssigneeUserId } from "./issueResponseAssigneeUserId";
import type { IssueResponseClosedAt } from "./issueResponseClosedAt";
import type { IssueResponseCreatedByUserId } from "./issueResponseCreatedByUserId";
import type { IssueResponseDatasetId } from "./issueResponseDatasetId";
import type { IssueResponseDescription } from "./issueResponseDescription";
import type { IssueResponsePriority } from "./issueResponsePriority";
import type { IssueResponseResolutionNote } from "./issueResponseResolutionNote";
import type { IssueResponseSeverity } from "./issueResponseSeverity";
import type { IssueResponseSourceExternalId } from "./issueResponseSourceExternalId";
import type { IssueResponseSourceExternalUrl } from "./issueResponseSourceExternalUrl";
import type { IssueResponseSourceProvider } from "./issueResponseSourceProvider";

/**
 * Single issue response.
 */
export interface IssueResponse {
  acknowledged_by: IssueResponseAcknowledgedBy;
  assignee_user_id: IssueResponseAssigneeUserId;
  author_type: string;
  closed_at: IssueResponseClosedAt;
  created_at: string;
  created_by_user_id: IssueResponseCreatedByUserId;
  dataset_id: IssueResponseDatasetId;
  description: IssueResponseDescription;
  id: string;
  labels: string[];
  number: number;
  priority: IssueResponsePriority;
  resolution_note: IssueResponseResolutionNote;
  severity: IssueResponseSeverity;
  source_external_id: IssueResponseSourceExternalId;
  source_external_url: IssueResponseSourceExternalUrl;
  source_provider: IssueResponseSourceProvider;
  status: string;
  title: string;
  updated_at: string;
}
