/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { IssueEventListResponseNextCursor } from "./issueEventListResponseNextCursor";
import type { IssueEventResponse } from "./issueEventResponse";

/**
 * Paginated event list response.
 */
export interface IssueEventListResponse {
  items: IssueEventResponse[];
  next_cursor?: IssueEventListResponseNextCursor;
  total: number;
}
