/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response for an issue comment.
 */
export interface IssueCommentResponse {
  author_user_id: string;
  body: string;
  created_at: string;
  id: string;
  issue_id: string;
  updated_at: string;
}
