/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { IssueResponse } from "./issueResponse";
import type { IssueListResponseNextCursor } from "./issueListResponseNextCursor";

/**
 * Paginated issue list response.
 */
export interface IssueListResponse {
  has_more: boolean;
  items: IssueResponse[];
  next_cursor: IssueListResponseNextCursor;
  total: number;
}
