/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { IssueListResponseNextCursor } from "./issueListResponseNextCursor";
import type { IssueResponse } from "./issueResponse";

/**
 * Paginated issue list response.
 */
export interface IssueListResponse {
  has_more: boolean;
  items: IssueResponse[];
  next_cursor: IssueListResponseNextCursor;
  total: number;
}
