/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { IssueEventResponseActorUserId } from "./issueEventResponseActorUserId";
import type { IssueEventResponsePayload } from "./issueEventResponsePayload";

/**
 * Response for an issue event.
 */
export interface IssueEventResponse {
  actor_user_id: IssueEventResponseActorUserId;
  created_at: string;
  event_type: string;
  id: string;
  issue_id: string;
  payload: IssueEventResponsePayload;
}
