/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { IssueUpdateAcknowledgedBy } from "./issueUpdateAcknowledgedBy";
import type { IssueUpdateAssigneeUserId } from "./issueUpdateAssigneeUserId";
import type { IssueUpdateDescription } from "./issueUpdateDescription";
import type { IssueUpdateLabels } from "./issueUpdateLabels";
import type { IssueUpdatePriority } from "./issueUpdatePriority";
import type { IssueUpdateResolutionNote } from "./issueUpdateResolutionNote";
import type { IssueUpdateSeverity } from "./issueUpdateSeverity";
import type { IssueUpdateStatus } from "./issueUpdateStatus";
import type { IssueUpdateTitle } from "./issueUpdateTitle";

/**
 * Request body for updating an issue.
 */
export interface IssueUpdate {
  acknowledged_by?: IssueUpdateAcknowledgedBy;
  assignee_user_id?: IssueUpdateAssigneeUserId;
  description?: IssueUpdateDescription;
  labels?: IssueUpdateLabels;
  priority?: IssueUpdatePriority;
  resolution_note?: IssueUpdateResolutionNote;
  severity?: IssueUpdateSeverity;
  status?: IssueUpdateStatus;
  title?: IssueUpdateTitle;
}
