/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { IssueCreateDatasetId } from "./issueCreateDatasetId";
import type { IssueCreateDescription } from "./issueCreateDescription";
import type { IssueCreatePriority } from "./issueCreatePriority";
import type { IssueCreateSeverity } from "./issueCreateSeverity";

/**
 * Request body for creating an issue.
 */
export interface IssueCreate {
  dataset_id?: IssueCreateDatasetId;
  description?: IssueCreateDescription;
  labels?: string[];
  priority?: IssueCreatePriority;
  severity?: IssueCreateSeverity;
  /**
   * @minLength 1
   * @maxLength 500
   */
  title: string;
}
