/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { KnowledgeCommentResponseAuthorId } from "./knowledgeCommentResponseAuthorId";
import type { KnowledgeCommentResponseAuthorName } from "./knowledgeCommentResponseAuthorName";
import type { KnowledgeCommentResponseParentId } from "./knowledgeCommentResponseParentId";

/**
 * Response for a knowledge comment.
 */
export interface KnowledgeCommentResponse {
  author_id: KnowledgeCommentResponseAuthorId;
  author_name: KnowledgeCommentResponseAuthorName;
  content: string;
  created_at: string;
  dataset_id: string;
  downvotes: number;
  id: string;
  parent_id: KnowledgeCommentResponseParentId;
  updated_at: string;
  upvotes: number;
}
