/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Request body for updating a knowledge comment.
 */
export interface KnowledgeCommentUpdate {
  /** @minLength 1 */
  content: string;
}
