/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { KnowledgeCommentCreateParentId } from "./knowledgeCommentCreateParentId";

/**
 * Request body for creating a knowledge comment.
 */
export interface KnowledgeCommentCreate {
  /** @minLength 1 */
  content: string;
  parent_id?: KnowledgeCommentCreateParentId;
}
