/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { LineageGraphResponseDatasets } from "./lineageGraphResponseDatasets";
import type { LineageEdgeResponse } from "./lineageEdgeResponse";
import type { LineageGraphResponseJobs } from "./lineageGraphResponseJobs";

/**
 * Response for a lineage graph.
 */
export interface LineageGraphResponse {
  datasets: LineageGraphResponseDatasets;
  edges: LineageEdgeResponse[];
  jobs: LineageGraphResponseJobs;
  root: string;
}
