/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Lineage edge.
 */
export interface LineageEdge {
  edge_type?: string;
  source: string;
  target: string;
}
