/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { LineageGraphResponseDatasets } from "./lineageGraphResponseDatasets";
import type { LineageEdge } from "./lineageEdge";
import type { LineageGraphResponseRoot } from "./lineageGraphResponseRoot";

/**
 * Lineage graph response.
 */
export interface LineageGraphResponse {
  datasets?: LineageGraphResponseDatasets;
  edges?: LineageEdge[];
  root?: LineageGraphResponseRoot;
}
