/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { LineageProviderResponse } from "./lineageProviderResponse";

/**
 * Response for listing lineage providers.
 */
export interface LineageProvidersResponse {
  providers: LineageProviderResponse[];
}
