/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ListMessagesApiV1IssuesIssueIdThreadsThreadIdMessagesGetParams = {
  /**
   * @minimum 0
   */
  after_seq?: number;
  /**
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
};
