/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ListDatasetsApiV1LineageDatasetsGetParams = {
  /**
   * Filter by platform
   */
  platform?: string | null;
  /**
   * Filter by database
   */
  database?: string | null;
  /**
   * Filter by schema
   */
  schema?: string | null;
  /**
   * Maximum results
   * @minimum 1
   * @maximum 1000
   */
  limit?: number;
};
