/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SessionSummary } from "./sessionSummary";

/**
 * Response from listing sessions.
 */
export interface ListSessionsResponse {
  sessions: SessionSummary[];
}
