/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ListIssuesApiV1IssuesGetParams = {
  /**
   * Filter by status
   */
  status?: string | null;
  /**
   * Filter by priority
   */
  priority?: string | null;
  /**
   * Filter by severity
   */
  severity?: string | null;
  /**
   * Filter by assignee
   */
  assignee?: string | null;
  /**
   * Full-text search
   */
  search?: string | null;
  /**
   * Pagination cursor
   */
  cursor?: string | null;
  /**
   * Max issues
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
