/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ListNotificationsApiV1NotificationsGetParams = {
  /**
   * Max notifications to return
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Pagination cursor
   */
  cursor?: string | null;
  /**
   * Only return unread notifications
   */
  unread_only?: boolean;
};
