/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ListIssueEventsApiV1IssuesIssueIdEventsGetParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  cursor?: string | null;
};
