/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ListDatasourceDatasetsApiV1V2DatasourcesDatasourceIdDatasetsGetParams =
  {
    table_type?: string | null;
    search?: string | null;
    /**
     * @minimum 1
     * @maximum 10000
     */
    limit?: number;
    /**
     * @minimum 0
     */
    offset?: number;
  };
