/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Cursor pointing to newest marked notification for resumability
 */
export type MarkAllReadResponseCursor = string | null;
