/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { MarkAllReadResponseCursor } from "./markAllReadResponseCursor";

/**
 * Response after marking all notifications as read.
 */
export interface MarkAllReadResponse {
  /** Cursor pointing to newest marked notification for resumability */
  cursor?: MarkAllReadResponseCursor;
  marked_count: number;
}
