/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { MessageCreateReplyToId } from "./messageCreateReplyToId";

/**
 * Request body for posting a message.
 */
export interface MessageCreate {
  ask_agent?: boolean;
  /**
   * @minLength 1
   * @maxLength 20000
   */
  body_md: string;
  reply_to_id?: MessageCreateReplyToId;
}
