/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Request body for editing a comment.
 */
export interface MessageUpdate {
  /**
   * @minLength 1
   * @maxLength 20000
   */
  body_md: string;
}
