/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Message role types.
 */
export type MessageRole = (typeof MessageRole)[keyof typeof MessageRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageRole = {
  user: "user",
  assistant: "assistant",
  system: "system",
  tool: "tool",
} as const;
