/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { MessageResponse } from "./messageResponse";

/**
 * A page of messages ordered by seq.
 */
export interface MessageListResponse {
  items: MessageResponse[];
}
