/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { MessageResponseAuthorUserId } from "./messageResponseAuthorUserId";
import type { MessageResponseDeletedAt } from "./messageResponseDeletedAt";
import type { MessageResponseEditedAt } from "./messageResponseEditedAt";
import type { MessageResponsePayload } from "./messageResponsePayload";
import type { MessageResponseReplyToId } from "./messageResponseReplyToId";
import type { MessageResponseRequestedByUserId } from "./messageResponseRequestedByUserId";
import type { MessageResponseRequestMessageId } from "./messageResponseRequestMessageId";

/**
 * One entry in a thread's timeline.
 */
export interface MessageResponse {
  asks_agent: boolean;
  author_kind: string;
  author_user_id: MessageResponseAuthorUserId;
  body_md: string;
  created_at: string;
  deleted_at: MessageResponseDeletedAt;
  edited_at: MessageResponseEditedAt;
  id: string;
  kind: string;
  payload: MessageResponsePayload;
  reply_to_id: MessageResponseReplyToId;
  request_message_id: MessageResponseRequestMessageId;
  requested_by_user_id: MessageResponseRequestedByUserId;
  rev: number;
  seq: number;
  status: string;
  thread_id: string;
  updated_at: string;
}
