/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { MessageRole } from "./messageRole";
import type { MessageResponseTokenCount } from "./messageResponseTokenCount";
import type { MessageResponseToolCalls } from "./messageResponseToolCalls";

/**
 * A message in a session.
 */
export interface MessageResponse {
  content: string;
  created_at: string;
  id: string;
  role: MessageRole;
  token_count?: MessageResponseTokenCount;
  tool_calls?: MessageResponseToolCalls;
}
