/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ModifyRequestComment } from "./modifyRequestComment";
import type { ModifyRequestModifications } from "./modifyRequestModifications";

/**
 * Request to approve with modifications.
 */
export interface ModifyRequest {
  comment?: ModifyRequestComment;
  modifications: ModifyRequestModifications;
}
