/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { NotificationListResponseNextCursor } from "./notificationListResponseNextCursor";
import type { NotificationResponse } from "./notificationResponse";

/**
 * Paginated notification list response.
 */
export interface NotificationListResponse {
  has_more: boolean;
  items: NotificationResponse[];
  next_cursor: NotificationListResponseNextCursor;
}
