/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type NotificationStreamApiV1NotificationsStreamGetParams = {
  /**
   * Resume from notification ID (for reconnect)
   */
  after?: string | null;
};
