/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { OperationalFactsResponseFreshness } from "./operationalFactsResponseFreshness";
import type { OperationalFactsResponseRecentRunsItem } from "./operationalFactsResponseRecentRunsItem";

/**
 * Operational facts about assets.
 */
export interface OperationalFactsResponse {
  freshness?: OperationalFactsResponseFreshness;
  recent_runs?: OperationalFactsResponseRecentRunsItem[];
}
