/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { OutcomeReviewNote } from "./outcomeReviewNote";
import type { OutcomeReviewVerdict } from "./outcomeReviewVerdict";

/**
 * A verdict on a finished investigation's root cause.
 */
export interface OutcomeReview {
  note?: OutcomeReviewNote;
  verdict: OutcomeReviewVerdict;
}
