/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type OutcomeReviewVerdict =
  (typeof OutcomeReviewVerdict)[keyof typeof OutcomeReviewVerdict];

export const OutcomeReviewVerdict = {
  confirmed: "confirmed",
  rejected: "rejected",
} as const;
