/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type OutcomeReviewVerdict =
  (typeof OutcomeReviewVerdict)[keyof typeof OutcomeReviewVerdict];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OutcomeReviewVerdict = {
  confirmed: "confirmed",
  rejected: "rejected",
} as const;
