/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { PageContextError } from "./pageContextError";
import type { PageContextPageData } from "./pageContextPageData";
import type { PageContextRouteParams } from "./pageContextRouteParams";

/**
 * Context about the page the user is currently viewing.
 */
export interface PageContext {
  errors?: PageContextError[];
  page_data?: PageContextPageData;
  page_title: string;
  page_type: string;
  route: string;
  route_params?: PageContextRouteParams;
  route_pattern: string;
}
