/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { PageContextErrorStackPreview } from "./pageContextErrorStackPreview";
import type { PageContextErrorStatus } from "./pageContextErrorStatus";
import type { PageContextErrorUrl } from "./pageContextErrorUrl";

/**
 * A frontend error captured by the error bus.
 */
export interface PageContextError {
  message: string;
  stack_preview?: PageContextErrorStackPreview;
  status?: PageContextErrorStatus;
  timestamp: number;
  /** Error type: api, react, or console */
  type: string;
  url?: PageContextErrorUrl;
}
