/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { PermissionGrantCreateAccessType } from "./permissionGrantCreateAccessType";
import type { PermissionGrantCreateDataSourceId } from "./permissionGrantCreateDataSourceId";
import type { PermissionGrantCreateGranteeType } from "./permissionGrantCreateGranteeType";
import type { PermissionGrantCreatePermission } from "./permissionGrantCreatePermission";
import type { PermissionGrantCreateResourceId } from "./permissionGrantCreateResourceId";
import type { PermissionGrantCreateTagId } from "./permissionGrantCreateTagId";

/**
 * Permission grant creation request.
 */
export interface PermissionGrantCreate {
  access_type: PermissionGrantCreateAccessType;
  data_source_id?: PermissionGrantCreateDataSourceId;
  grantee_id: string;
  grantee_type: PermissionGrantCreateGranteeType;
  permission: PermissionGrantCreatePermission;
  resource_id?: PermissionGrantCreateResourceId;
  resource_type?: string;
  tag_id?: PermissionGrantCreateTagId;
}
