/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type PermissionGrantCreatePermission =
  (typeof PermissionGrantCreatePermission)[keyof typeof PermissionGrantCreatePermission];

export const PermissionGrantCreatePermission = {
  read: "read",
  write: "write",
  admin: "admin",
} as const;
