/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type PermissionGrantCreateGranteeType =
  (typeof PermissionGrantCreateGranteeType)[keyof typeof PermissionGrantCreateGranteeType];

export const PermissionGrantCreateGranteeType = {
  user: "user",
  team: "team",
} as const;
