/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { PublishRequestNote } from "./publishRequestNote";

/**
 * Request body for publishing scratch-chat messages to the shared thread.
 */
export interface PublishRequest {
  /**
   * @minItems 1
   * @maxItems 50
   */
  message_ids: string[];
  note?: PublishRequestNote;
}
