/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { QueryResultResponseColumnsItem } from "./queryResultResponseColumnsItem";
import type { QueryResultResponseError } from "./queryResultResponseError";
import type { QueryResultResponseRowsItem } from "./queryResultResponseRowsItem";

/**
 * What the agent saw when it ran a query.
 */
export interface QueryResultResponse {
  columns: QueryResultResponseColumnsItem[];
  created_at: string;
  dialect: string;
  duration_ms: number;
  error: QueryResultResponseError;
  id: string;
  message_id: string;
  row_count: number;
  rows: QueryResultResponseRowsItem[];
  sql: string;
  tool_call_id: string;
  truncated: boolean;
}
