/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Request to execute a query.
 */
export interface QueryRequest {
  query: string;
  timeout_seconds?: number;
}
