/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { RecentCatchResponseColumn } from "./recentCatchResponseColumn";
import type { RecentCatchResponseFailureMessage } from "./recentCatchResponseFailureMessage";

/**
 * A recent test failure catch.
 */
export interface RecentCatchResponse {
  column: RecentCatchResponseColumn;
  failure_message: RecentCatchResponseFailureMessage;
  investigation_id: string;
  run_at: string;
  table: string;
  test_id: string;
  test_type: string;
}
