/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { RepoMappingResponse } from "./repoMappingResponse";

/**
 * Response for a list of dataset-to-repository mappings.
 */
export interface RepoMappingListResponse {
  items: RepoMappingResponse[];
  total: number;
}
