/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { RepoMappingResponseBranch } from "./repoMappingResponseBranch";
import type { RepoMappingResponseFilePath } from "./repoMappingResponseFilePath";
import type { RepoMappingResponseJobName } from "./repoMappingResponseJobName";
import type { RepoMappingResponseLastVerifiedAt } from "./repoMappingResponseLastVerifiedAt";
import type { RepoMappingResponseMetadata } from "./repoMappingResponseMetadata";
import type { RepoMappingResponseUpdatedAt } from "./repoMappingResponseUpdatedAt";

/**
 * Response for a dataset-to-repository mapping.
 */
export interface RepoMappingResponse {
  branch: RepoMappingResponseBranch;
  confidence: number;
  confirmed: boolean;
  created_at: string;
  dataset_pattern: string;
  file_path: RepoMappingResponseFilePath;
  id: string;
  job_name: RepoMappingResponseJobName;
  last_verified_at?: RepoMappingResponseLastVerifiedAt;
  metadata: RepoMappingResponseMetadata;
  pattern_type: string;
  priority: number;
  repo_name: string;
  repo_owner: string;
  source: string;
  updated_at?: RepoMappingResponseUpdatedAt;
}
