/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ResolvedRepoResponseBranch } from "./resolvedRepoResponseBranch";
import type { ResolvedRepoResponseFilePath } from "./resolvedRepoResponseFilePath";
import type { ResolvedRepoResponseJobName } from "./resolvedRepoResponseJobName";

/**
 * A resolved repository match for a dataset.
 */
export interface ResolvedRepoResponse {
  branch: ResolvedRepoResponseBranch;
  confidence: number;
  file_path: ResolvedRepoResponseFilePath;
  job_name: ResolvedRepoResponseJobName;
  repo_name: string;
  repo_owner: string;
  source: string;
}
