/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { AssetRefRequest } from "./assetRefRequest";
import type { ResolvedAssetResponseDatasetType } from "./resolvedAssetResponseDatasetType";
import type { ResolvedAssetResponseDatasourceId } from "./resolvedAssetResponseDatasourceId";

/**
 * Resolved asset in response.
 */
export interface ResolvedAssetResponse {
  asset: AssetRefRequest;
  /** Canonical URN */
  dataset_id: string;
  /** TABLE, VIEW, MODEL, etc. */
  dataset_type?: ResolvedAssetResponseDatasetType;
  datasource_id?: ResolvedAssetResponseDatasourceId;
}
