/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * TABLE, VIEW, MODEL, etc.
 */
export type ResolvedAssetResponseDatasetType = string | null;
