/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { RunStatus } from "./runStatus";

/**
 * Response for a created run.
 */
export interface RunResponse {
  bundle_hash: string;
  bundle_id: string;
  created_at: string;
  events_url: string;
  run_id: string;
  status: RunStatus;
}
