/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Status of a run.
 */
export type RunStatus = (typeof RunStatus)[keyof typeof RunStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunStatus = {
  running: "running",
  completed: "completed",
  failed: "failed",
  cancelled: "cancelled",
} as const;
