/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SaveCredentialsRequestRole } from "./saveCredentialsRequestRole";
import type { SaveCredentialsRequestWarehouse } from "./saveCredentialsRequestWarehouse";

/**
 * Request to save user credentials for a datasource.
 */
export interface SaveCredentialsRequest {
  /** @minLength 1 */
  password: string;
  /** Role for Snowflake */
  role?: SaveCredentialsRequestRole;
  /**
   * @minLength 1
   * @maxLength 255
   */
  username: string;
  /** Warehouse for Snowflake */
  warehouse?: SaveCredentialsRequestWarehouse;
}
