/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SchemaCommentCreateParentId } from "./schemaCommentCreateParentId";

/**
 * Request body for creating a schema comment.
 */
export interface SchemaCommentCreate {
  /** @minLength 1 */
  content: string;
  /** @minLength 1 */
  field_name: string;
  parent_id?: SchemaCommentCreateParentId;
}
