/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SchemaCommentResponseAuthorId } from "./schemaCommentResponseAuthorId";
import type { SchemaCommentResponseAuthorName } from "./schemaCommentResponseAuthorName";
import type { SchemaCommentResponseParentId } from "./schemaCommentResponseParentId";

/**
 * Response for a schema comment.
 */
export interface SchemaCommentResponse {
  author_id: SchemaCommentResponseAuthorId;
  author_name: SchemaCommentResponseAuthorName;
  content: string;
  created_at: string;
  dataset_id: string;
  downvotes: number;
  field_name: string;
  id: string;
  parent_id: SchemaCommentResponseParentId;
  updated_at: string;
  upvotes: number;
}
