/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SchemaResponseModelCatalogsItem } from "./schemaResponseModelCatalogsItem";
import type { SchemaResponseModelTablesItem } from "./schemaResponseModelTablesItem";

/**
 * Response for schema discovery.
 */
export interface SchemaResponseModel {
  catalogs: SchemaResponseModelCatalogsItem[];
  fetched_at: string;
  source_category: string;
  source_id: string;
  source_type: string;
  /** Flattened list of tables (schema.table format) for convenience */
  tables?: SchemaResponseModelTablesItem[];
}
