/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SCIMGroupCreateRequestExternalId } from "./sCIMGroupCreateRequestExternalId";
import type { SCIMGroupCreateRequestMembers } from "./sCIMGroupCreateRequestMembers";

/**
 * SCIM group creation request.
 */
export interface SCIMGroupCreateRequest {
  displayName: string;
  externalId?: SCIMGroupCreateRequestExternalId;
  members?: SCIMGroupCreateRequestMembers;
  schemas: string[];
}
