/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type SearchAssetInstancesApiV1AssetInstancesSearchGetParams = {
  /**
   * Search query (min 1 char)
   */
  q: string;
  /**
   * Max results (default 10, max 100)
   */
  limit?: number;
  /**
   * Opaque pagination cursor
   */
  cursor?: string | null;
  /**
   * Filter to single datasource
   */
  datasource_id?: string | null;
};
