/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SessionSummaryTitle } from "./sessionSummaryTitle";

/**
 * Summary of a session for listing.
 */
export interface SessionSummary {
  created_at: string;
  id: string;
  last_activity: string;
  message_count: number;
  title: SessionSummaryTitle;
  token_count: number;
}
