/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { MessageResponse } from "./messageResponse";
import type { SessionDetailResponseParentInvestigationId } from "./sessionDetailResponseParentInvestigationId";
import type { SessionDetailResponseTitle } from "./sessionDetailResponseTitle";

/**
 * Full session details with messages.
 */
export interface SessionDetailResponse {
  created_at: string;
  id: string;
  investigation_id: string;
  last_activity: string;
  messages: MessageResponse[];
  parent_investigation_id?: SessionDetailResponseParentInvestigationId;
  title: SessionDetailResponseTitle;
  token_count: number;
}
