/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Minutes to acknowledge (OPEN -> TRIAGED)
 */
export type SeverityOverrideTimeToAcknowledge = number | null;
