/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Minutes to resolve (any -> RESOLVED)
 */
export type SeverityOverrideTimeToResolve = number | null;
