/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SeverityOverrideTimeToAcknowledge } from "./severityOverrideTimeToAcknowledge";
import type { SeverityOverrideTimeToProgress } from "./severityOverrideTimeToProgress";
import type { SeverityOverrideTimeToResolve } from "./severityOverrideTimeToResolve";

/**
 * Override SLA times for a specific severity.
 */
export interface SeverityOverride {
  /** Minutes to acknowledge (OPEN -> TRIAGED) */
  time_to_acknowledge?: SeverityOverrideTimeToAcknowledge;
  /** Minutes to progress (TRIAGED -> IN_PROGRESS) */
  time_to_progress?: SeverityOverrideTimeToProgress;
  /** Minutes to resolve (any -> RESOLVED) */
  time_to_resolve?: SeverityOverrideTimeToResolve;
}
