/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Minutes to progress (TRIAGED -> IN_PROGRESS)
 */
export type SeverityOverrideTimeToProgress = number | null;
