/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SeverityOverride } from "./severityOverride";

export type SLAPolicyUpdateSeverityOverridesAnyOf = {
  [key: string]: SeverityOverride;
};
