/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SLAPolicyResponseSeverityOverrides } from "./sLAPolicyResponseSeverityOverrides";
import type { SLAPolicyResponseTimeToAcknowledge } from "./sLAPolicyResponseTimeToAcknowledge";
import type { SLAPolicyResponseTimeToProgress } from "./sLAPolicyResponseTimeToProgress";
import type { SLAPolicyResponseTimeToResolve } from "./sLAPolicyResponseTimeToResolve";

/**
 * SLA policy response.
 */
export interface SLAPolicyResponse {
  created_at: string;
  id: string;
  is_default: boolean;
  name: string;
  severity_overrides: SLAPolicyResponseSeverityOverrides;
  tenant_id: string;
  time_to_acknowledge: SLAPolicyResponseTimeToAcknowledge;
  time_to_progress: SLAPolicyResponseTimeToProgress;
  time_to_resolve: SLAPolicyResponseTimeToResolve;
  updated_at: string;
}
