/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SLAPolicyCreateSeverityOverrides } from "./sLAPolicyCreateSeverityOverrides";
import type { SLAPolicyCreateTimeToAcknowledge } from "./sLAPolicyCreateTimeToAcknowledge";
import type { SLAPolicyCreateTimeToProgress } from "./sLAPolicyCreateTimeToProgress";
import type { SLAPolicyCreateTimeToResolve } from "./sLAPolicyCreateTimeToResolve";

/**
 * Request to create an SLA policy.
 */
export interface SLAPolicyCreate {
  is_default?: boolean;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** Per-severity overrides (low, medium, high, critical) */
  severity_overrides?: SLAPolicyCreateSeverityOverrides;
  /** Minutes to acknowledge */
  time_to_acknowledge?: SLAPolicyCreateTimeToAcknowledge;
  /** Minutes to progress */
  time_to_progress?: SLAPolicyCreateTimeToProgress;
  /** Minutes to resolve */
  time_to_resolve?: SLAPolicyCreateTimeToResolve;
}
