/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SLAPolicyUpdateIsDefault } from "./sLAPolicyUpdateIsDefault";
import type { SLAPolicyUpdateName } from "./sLAPolicyUpdateName";
import type { SLAPolicyUpdateSeverityOverrides } from "./sLAPolicyUpdateSeverityOverrides";
import type { SLAPolicyUpdateTimeToAcknowledge } from "./sLAPolicyUpdateTimeToAcknowledge";
import type { SLAPolicyUpdateTimeToProgress } from "./sLAPolicyUpdateTimeToProgress";
import type { SLAPolicyUpdateTimeToResolve } from "./sLAPolicyUpdateTimeToResolve";

/**
 * Request to update an SLA policy.
 */
export interface SLAPolicyUpdate {
  is_default?: SLAPolicyUpdateIsDefault;
  name?: SLAPolicyUpdateName;
  severity_overrides?: SLAPolicyUpdateSeverityOverrides;
  time_to_acknowledge?: SLAPolicyUpdateTimeToAcknowledge;
  time_to_progress?: SLAPolicyUpdateTimeToProgress;
  time_to_resolve?: SLAPolicyUpdateTimeToResolve;
}
