/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SLAPolicyCreateSeverityOverridesAnyOf } from "./sLAPolicyCreateSeverityOverridesAnyOf";

/**
 * Per-severity overrides (low, medium, high, critical)
 */
export type SLAPolicyCreateSeverityOverrides =
  SLAPolicyCreateSeverityOverridesAnyOf | null;
