/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SLAPolicyResponse } from "./sLAPolicyResponse";

/**
 * Paginated SLA policy list response.
 */
export interface SLAPolicyListResponse {
  items: SLAPolicyResponse[];
  total: number;
}
