/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Valid checkpoint values for snapshot download.
 */
export type SnapshotCheckpointParam =
  (typeof SnapshotCheckpointParam)[keyof typeof SnapshotCheckpointParam];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SnapshotCheckpointParam = {
  start: "start",
  hypothesis_generated: "hypothesis_generated",
  evidence_collected: "evidence_collected",
  complete: "complete",
  failed: "failed",
} as const;
