/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SnapshotListItemSizeBytes } from "./snapshotListItemSizeBytes";

/**
 * Snapshot metadata for listing.
 */
export interface SnapshotListItem {
  captured_at: string;
  checkpoint: string;
  size_bytes?: SnapshotListItemSizeBytes;
  storage_path: string;
}
