/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SourceTypeResponse } from "./sourceTypeResponse";

/**
 * Response for listing source types.
 */
export interface SourceTypesResponse {
  types: SourceTypeResponse[];
}
