/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ConfigSchema } from "./configSchema";
import type { SourceTypeResponseCapabilities } from "./sourceTypeResponseCapabilities";

/**
 * Response for a source type definition.
 */
export interface SourceTypeResponse {
  capabilities: SourceTypeResponseCapabilities;
  category: string;
  config_schema: ConfigSchema;
  description: string;
  display_name: string;
  icon: string;
  type: string;
}
