/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response for starting an investigation.
 */
export interface StartInvestigationResponse {
  investigation_id: string;
  main_branch_id: string;
  status?: string;
}
