/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { StatsResponseColumns } from "./statsResponseColumns";
import type { StatsResponseRowCount } from "./statsResponseRowCount";

/**
 * Response for column statistics.
 */
export interface StatsResponse {
  columns: StatsResponseColumns;
  row_count?: StatsResponseRowCount;
  table: string;
}
