/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SteerResponseActorUserId } from "./steerResponseActorUserId";
import type { SteerResponseAppliedAt } from "./steerResponseAppliedAt";
import type { SteerResponseAppliedPhase } from "./steerResponseAppliedPhase";
import type { SteerResponseHypothesisId } from "./steerResponseHypothesisId";
import type { SteerResponseIssueId } from "./steerResponseIssueId";
import type { SteerResponseMessageId } from "./steerResponseMessageId";
import type { SteerResponseOutcome } from "./steerResponseOutcome";

/**
 * A steer and how it ended.
 */
export interface SteerResponse {
  actor_user_id: SteerResponseActorUserId;
  applied_at: SteerResponseAppliedAt;
  applied_phase: SteerResponseAppliedPhase;
  created_at: string;
  hypothesis_id: SteerResponseHypothesisId;
  id: string;
  investigation_id: string;
  issue_id: SteerResponseIssueId;
  kind: string;
  message_id: SteerResponseMessageId;
  outcome: SteerResponseOutcome;
  status: string;
  text: string;
}
