/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { SteerCreateHypothesisId } from "./steerCreateHypothesisId";
import type { SteerCreateKind } from "./steerCreateKind";
import type { SteerCreateProposalMessageId } from "./steerCreateProposalMessageId";

/**
 * A steer for a running investigation.
 */
export interface SteerCreate {
  hypothesis_id?: SteerCreateHypothesisId;
  kind: SteerCreateKind;
  proposal_message_id?: SteerCreateProposalMessageId;
  /** @maxLength 2000 */
  text?: string;
}
