/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type SteerCreateKind =
  (typeof SteerCreateKind)[keyof typeof SteerCreateKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SteerCreateKind = {
  add_context: "add_context",
  rule_out: "rule_out",
  add_hypothesis: "add_hypothesis",
  stop_and_synthesize: "stop_and_synthesize",
} as const;
