/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { StoreEvidenceRequestContent } from "./storeEvidenceRequestContent";

/**
 * Request to store evidence for a run.
 */
export interface StoreEvidenceRequest {
  /** Evidence content */
  content: StoreEvidenceRequestContent;
  /** Evidence kind discriminator */
  kind: string;
}
