/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type StreamThreadApiV1IssuesIssueIdThreadsThreadIdStreamGetParams = {
  after?: number | null;
};
