/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type StreamEventsApiV1InvestigationsInvestigationIdEventsGetParams = {
  /**
   * Resume from this sequence number
   */
  seq?: number | null;
};
