/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response for sync trigger.
 */
export interface SyncTriggerResponse {
  message: string;
  sync_status: string;
}
