/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TagResponse } from "./tagResponse";

/**
 * Response for listing tags.
 */
export interface TagListResponse {
  tags: TagResponse[];
  total: number;
}
