/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Tag response.
 */
export interface TagResponse {
  color: string;
  id: string;
  name: string;
}
