/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TeamQueueLimitsUpdateBatchSize } from "./teamQueueLimitsUpdateBatchSize";
import type { TeamQueueLimitsUpdateBurstSize } from "./teamQueueLimitsUpdateBurstSize";
import type { TeamQueueLimitsUpdateMaxConcurrent } from "./teamQueueLimitsUpdateMaxConcurrent";
import type { TeamQueueLimitsUpdateRateLimitPerMinute } from "./teamQueueLimitsUpdateRateLimitPerMinute";

/**
 * Team queue limits update request.
 */
export interface TeamQueueLimitsUpdate {
  batch_size?: TeamQueueLimitsUpdateBatchSize;
  burst_size?: TeamQueueLimitsUpdateBurstSize;
  max_concurrent?: TeamQueueLimitsUpdateMaxConcurrent;
  rate_limit_per_minute?: TeamQueueLimitsUpdateRateLimitPerMinute;
}
