/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TeamPolicyFullResponsePolicy } from "./teamPolicyFullResponsePolicy";
import type { TeamPolicyFullResponseQueueLimits } from "./teamPolicyFullResponseQueueLimits";
import type { TeamPolicyOverrideResponse } from "./teamPolicyOverrideResponse";

/**
 * Full team policy response including overrides and queue limits.
 */
export interface TeamPolicyFullResponse {
  overrides?: TeamPolicyOverrideResponse[];
  policy?: TeamPolicyFullResponsePolicy;
  queue_limits?: TeamPolicyFullResponseQueueLimits;
}
