/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TeamPolicyUpdateAutoInvestigateMinSeverity } from "./teamPolicyUpdateAutoInvestigateMinSeverity";
import type { TeamPolicyUpdateDefaultAction } from "./teamPolicyUpdateDefaultAction";
import type { TeamPolicyUpdateReviewRequiredMaxSeverity } from "./teamPolicyUpdateReviewRequiredMaxSeverity";
import type { TeamPolicyUpdateSources } from "./teamPolicyUpdateSources";

/**
 * Team policy update request.
 */
export interface TeamPolicyUpdate {
  auto_investigate_min_severity?: TeamPolicyUpdateAutoInvestigateMinSeverity;
  default_action?: TeamPolicyUpdateDefaultAction;
  review_required_max_severity?: TeamPolicyUpdateReviewRequiredMaxSeverity;
  sources?: TeamPolicyUpdateSources;
}
