/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TeamPolicyOverrideUpdateAutoInvestigateMinSeverity } from "./teamPolicyOverrideUpdateAutoInvestigateMinSeverity";
import type { TeamPolicyOverrideUpdateDefaultAction } from "./teamPolicyOverrideUpdateDefaultAction";
import type { TeamPolicyOverrideUpdateReviewRequiredMaxSeverity } from "./teamPolicyOverrideUpdateReviewRequiredMaxSeverity";

/**
 * Update a policy override.
 */
export interface TeamPolicyOverrideUpdate {
  auto_investigate_min_severity?: TeamPolicyOverrideUpdateAutoInvestigateMinSeverity;
  default_action?: TeamPolicyOverrideUpdateDefaultAction;
  review_required_max_severity?: TeamPolicyOverrideUpdateReviewRequiredMaxSeverity;
}
