/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TeamPolicyOverrideResponseAutoInvestigateMinSeverity } from "./teamPolicyOverrideResponseAutoInvestigateMinSeverity";
import type { TeamPolicyOverrideResponseDatasetId } from "./teamPolicyOverrideResponseDatasetId";
import type { TeamPolicyOverrideResponseDefaultAction } from "./teamPolicyOverrideResponseDefaultAction";
import type { TeamPolicyOverrideResponseReviewRequiredMaxSeverity } from "./teamPolicyOverrideResponseReviewRequiredMaxSeverity";
import type { TeamPolicyOverrideResponseTagId } from "./teamPolicyOverrideResponseTagId";

/**
 * Team policy override response.
 */
export interface TeamPolicyOverrideResponse {
  auto_investigate_min_severity?: TeamPolicyOverrideResponseAutoInvestigateMinSeverity;
  dataset_id?: TeamPolicyOverrideResponseDatasetId;
  default_action?: TeamPolicyOverrideResponseDefaultAction;
  id: string;
  is_active?: boolean;
  review_required_max_severity?: TeamPolicyOverrideResponseReviewRequiredMaxSeverity;
  tag_id?: TeamPolicyOverrideResponseTagId;
  team_id: string;
}
