/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TeamPolicyOverrideCreateAutoInvestigateMinSeverity } from "./teamPolicyOverrideCreateAutoInvestigateMinSeverity";
import type { TeamPolicyOverrideCreateDatasetId } from "./teamPolicyOverrideCreateDatasetId";
import type { TeamPolicyOverrideCreateDefaultAction } from "./teamPolicyOverrideCreateDefaultAction";
import type { TeamPolicyOverrideCreateReviewRequiredMaxSeverity } from "./teamPolicyOverrideCreateReviewRequiredMaxSeverity";
import type { TeamPolicyOverrideCreateTagId } from "./teamPolicyOverrideCreateTagId";

/**
 * Create a policy override.
 */
export interface TeamPolicyOverrideCreate {
  auto_investigate_min_severity?: TeamPolicyOverrideCreateAutoInvestigateMinSeverity;
  dataset_id?: TeamPolicyOverrideCreateDatasetId;
  default_action?: TeamPolicyOverrideCreateDefaultAction;
  review_required_max_severity?: TeamPolicyOverrideCreateReviewRequiredMaxSeverity;
  tag_id?: TeamPolicyOverrideCreateTagId;
}
