/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Team queue limits response.
 */
export interface TeamQueueLimitsResponse {
  batch_size?: number;
  burst_size?: number;
  id: string;
  is_active?: boolean;
  max_concurrent?: number;
  rate_limit_per_minute?: number;
  team_id: string;
}
