/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TeamPolicyResponseAutoInvestigateMinSeverity } from "./teamPolicyResponseAutoInvestigateMinSeverity";
import type { TeamPolicyResponseReviewRequiredMaxSeverity } from "./teamPolicyResponseReviewRequiredMaxSeverity";

/**
 * Team policy response.
 */
export interface TeamPolicyResponse {
  auto_investigate_min_severity?: TeamPolicyResponseAutoInvestigateMinSeverity;
  default_action: string;
  id: string;
  is_active?: boolean;
  review_required_max_severity?: TeamPolicyResponseReviewRequiredMaxSeverity;
  sources?: string[];
  team_id: string;
}
