/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TemporalStatusResponseCurrentStep } from "./temporalStatusResponseCurrentStep";
import type { TemporalStatusResponseEvidenceCount } from "./temporalStatusResponseEvidenceCount";
import type { TemporalStatusResponseHypotheses } from "./temporalStatusResponseHypotheses";
import type { TemporalStatusResponseHypothesesCount } from "./temporalStatusResponseHypothesesCount";
import type { TemporalStatusResponseHypothesesEvaluated } from "./temporalStatusResponseHypothesesEvaluated";
import type { TemporalStatusResponseIsCancelled } from "./temporalStatusResponseIsCancelled";
import type { TemporalStatusResponseIsComplete } from "./temporalStatusResponseIsComplete";
import type { TemporalStatusResponsePendingSteers } from "./temporalStatusResponsePendingSteers";
import type { TemporalStatusResponseProgress } from "./temporalStatusResponseProgress";

/**
 * Status response for Temporal-based investigations.
 */
export interface TemporalStatusResponse {
  current_step?: TemporalStatusResponseCurrentStep;
  evidence_count?: TemporalStatusResponseEvidenceCount;
  hypotheses?: TemporalStatusResponseHypotheses;
  hypotheses_count?: TemporalStatusResponseHypothesesCount;
  hypotheses_evaluated?: TemporalStatusResponseHypothesesEvaluated;
  investigation_id: string;
  is_cancelled?: TemporalStatusResponseIsCancelled;
  is_complete?: TemporalStatusResponseIsComplete;
  pending_steers?: TemporalStatusResponsePendingSteers;
  progress?: TemporalStatusResponseProgress;
  workflow_status: string;
}
