/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TestConnectionResponseLatencyMs } from "./testConnectionResponseLatencyMs";
import type { TestConnectionResponseServerVersion } from "./testConnectionResponseServerVersion";

/**
 * Response for testing a connection.
 */
export interface TestConnectionResponse {
  latency_ms?: TestConnectionResponseLatencyMs;
  message: string;
  server_version?: TestConnectionResponseServerVersion;
  success: boolean;
}
