/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TestAdoptionRequestAdoptedBy } from "./testAdoptionRequestAdoptedBy";

/**
 * Request to mark a test as adopted.
 */
export interface TestAdoptionRequest {
  adopted_by?: TestAdoptionRequestAdoptedBy;
  test_id: string;
}
