/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TestRunResultRequestFailureMessage } from "./testRunResultRequestFailureMessage";

/**
 * Request to record a test run result.
 */
export interface TestRunResultRequest {
  failure_message?: TestRunResultRequestFailureMessage;
  passed: boolean;
  test_id: string;
}
