/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Test tracking statistics response.
 */
export interface TestTrackingStatsResponse {
  adoption_rate: number;
  effectiveness_rate: number;
  issues_caught: number;
  tests_adopted: number;
  tests_generated: number;
  tests_run: number;
}
