/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { TestConnectionResponseError } from "./testConnectionResponseError";
import type { TestConnectionResponseTablesAccessible } from "./testConnectionResponseTablesAccessible";

/**
 * Response for testing credentials.
 */
export interface TestConnectionResponse {
  error?: TestConnectionResponseError;
  success: boolean;
  tables_accessible?: TestConnectionResponseTablesAccessible;
}
