/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ThreadResponse } from "./threadResponse";

/**
 * The shared thread followed by the caller's scratch threads.
 */
export interface ThreadListResponse {
  items: ThreadResponse[];
}
