/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type ThreadResponseKind =
  (typeof ThreadResponseKind)[keyof typeof ThreadResponseKind];

export const ThreadResponseKind = {
  shared: "shared",
  scratch: "scratch",
} as const;
