/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { ThreadResponseKind } from "./threadResponseKind";
import type { ThreadResponseOwnerUserId } from "./threadResponseOwnerUserId";
import type { ThreadResponseTitle } from "./threadResponseTitle";

/**
 * A shared or scratch thread.
 */
export interface ThreadResponse {
  created_at: string;
  id: string;
  issue_id: string;
  kind: ThreadResponseKind;
  owner_user_id: ThreadResponseOwnerUserId;
  title: ThreadResponseTitle;
}
