/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * The period the investigation should look at.
 */
export interface TimeWindow {
  from: string;
  to: string;
}
