/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { UpdateRepoMappingRequestBranch } from "./updateRepoMappingRequestBranch";
import type { UpdateRepoMappingRequestDatasetPattern } from "./updateRepoMappingRequestDatasetPattern";
import type { UpdateRepoMappingRequestFilePath } from "./updateRepoMappingRequestFilePath";
import type { UpdateRepoMappingRequestJobName } from "./updateRepoMappingRequestJobName";
import type { UpdateRepoMappingRequestMetadata } from "./updateRepoMappingRequestMetadata";
import type { UpdateRepoMappingRequestPatternType } from "./updateRepoMappingRequestPatternType";
import type { UpdateRepoMappingRequestRepoName } from "./updateRepoMappingRequestRepoName";
import type { UpdateRepoMappingRequestRepoOwner } from "./updateRepoMappingRequestRepoOwner";

/**
 * Request to update a dataset-to-repository mapping.
 */
export interface UpdateRepoMappingRequest {
  branch?: UpdateRepoMappingRequestBranch;
  dataset_pattern?: UpdateRepoMappingRequestDatasetPattern;
  file_path?: UpdateRepoMappingRequestFilePath;
  job_name?: UpdateRepoMappingRequestJobName;
  metadata?: UpdateRepoMappingRequestMetadata;
  pattern_type?: UpdateRepoMappingRequestPatternType;
  repo_name?: UpdateRepoMappingRequestRepoName;
  repo_owner?: UpdateRepoMappingRequestRepoOwner;
}
