/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

export type UpdateUserRequestRole =
  | (typeof UpdateUserRequestRole)[keyof typeof UpdateUserRequestRole]
  | null;

export const UpdateUserRequestRole = {
  admin: "admin",
  member: "member",
  viewer: "viewer",
} as const;
