/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { UpdateGitRepoRequestDefaultBranch } from "./updateGitRepoRequestDefaultBranch";
import type { UpdateGitRepoRequestName } from "./updateGitRepoRequestName";
import type { UpdateGitRepoRequestTrackedPaths } from "./updateGitRepoRequestTrackedPaths";

/**
 * Request to update a git repository.
 */
export interface UpdateGitRepoRequest {
  default_branch?: UpdateGitRepoRequestDefaultBranch;
  name?: UpdateGitRepoRequestName;
  tracked_paths?: UpdateGitRepoRequestTrackedPaths;
}
