/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Usage metrics response.
 */
export interface UsageMetricsResponse {
  investigations: number;
  llm_cost: number;
  llm_tokens: number;
  query_executions: number;
  total_cost: number;
}
