/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { UserInputRequestAction } from "./userInputRequestAction";
import type { UserInputRequestData } from "./userInputRequestData";

/**
 * Request body for sending user input to an investigation.
 */
export interface UserInputRequest {
  action?: UserInputRequestAction;
  data?: UserInputRequestData;
  feedback: string;
}
