/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response for a watcher.
 */
export interface WatcherResponse {
  created_at: string;
  user_id: string;
}
