/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { WatcherResponse } from "./watcherResponse";

/**
 * Watcher list response.
 */
export interface WatcherListResponse {
  items: WatcherResponse[];
  total: number;
}
