/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */
import type { WebhookIssueResponseInvestigationId } from "./webhookIssueResponseInvestigationId";
import type { WebhookIssueResponsePolicyAction } from "./webhookIssueResponsePolicyAction";

/**
 * Response from webhook issue creation.
 */
export interface WebhookIssueResponse {
  created: boolean;
  id: string;
  investigation_id?: WebhookIssueResponseInvestigationId;
  number: number;
  policy_action?: WebhookIssueResponsePolicyAction;
  status: string;
}
