/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Response from webhook issue creation.
 */
export interface WebhookIssueResponse {
  created: boolean;
  id: string;
  number: number;
  status: string;
}
