/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * dataing
 * Autonomous Data Quality Investigation
 * OpenAPI spec version: 2.0.0
 */

/**
 * Weekly usage statistics response.
 */
export interface WeeklyUsageResponse {
  active_teams: number;
  investigations_completed: number;
  investigations_started: number;
  issues_created: number;
  issues_resolved: number;
  resolution_rate: number;
  week_start: string;
}
