"""Investigation export utilities for markdown report generation."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from jinja2 import Environment

# Markdown report template
MARKDOWN_TEMPLATE = """\
# Investigation Report: {{ investigation_id }}

**Status:** {{ status }}{% if confidence %} | **Confidence:** {{ confidence_pct }}%{% endif %}

**Generated:** {{ generated_at }}

---

## Summary

{% if root_cause -%}
{{ root_cause }}
{%- else -%}
_No root cause identified yet._
{%- endif %}

{% if evidence -%}
## Evidence Collected

{% for item in evidence -%}
### {{ loop.index }}. {{ item.kind | default("Evidence") | title | replace("_", " ") }}

{% if item.query or item.sql -%}
```sql
{{ item.query | default(item.sql) | truncate_sql }}
```

{% endif -%}
{% if item.interpretation -%}
**Interpretation:** {{ item.interpretation }}
{% endif -%}
{% if item.supports_hypothesis is not none -%}
**Verdict:** {{ "Supports" if item.supports_hypothesis else "Refutes" }} hypothesis
{% endif -%}
{% if item.confidence -%}
**Confidence:** {{ (item.confidence * 100) | round | int }}%
{% endif %}

{% endfor -%}
{% else -%}
_No evidence collected yet._

{% endif -%}

{% if recommendations -%}
## Recommendations

{% for rec in recommendations -%}
- {{ rec }}
{% endfor %}
{% endif -%}

---

*Generated by Dataing CLI*
"""


def _truncate_sql(sql: str, max_length: int = 2000) -> str:
    """Truncate SQL query if too long.

    Args:
        sql: The SQL query string.
        max_length: Maximum length before truncation.

    Returns:
        Truncated SQL with marker if needed.
    """
    if len(sql) <= max_length:
        return sql
    return sql[:max_length] + "\n-- ... (truncated)"


def render_markdown(investigation: dict[str, Any]) -> str:
    """Render investigation data as markdown report.

    Args:
        investigation: Investigation state dict with fields:
            - investigation_id: str
            - status: str
            - main_branch: dict with synthesis and evidence

    Returns:
        Formatted markdown string.
    """
    env = Environment(trim_blocks=True, lstrip_blocks=True)
    env.filters["truncate_sql"] = _truncate_sql
    template = env.from_string(MARKDOWN_TEMPLATE)

    # Extract data from investigation
    main_branch = investigation.get("main_branch", {})
    synthesis = main_branch.get("synthesis") or {}
    evidence = main_branch.get("evidence", [])

    # Get confidence and convert to percentage
    confidence = synthesis.get("confidence")
    confidence_pct = None
    if confidence is not None:
        # Handle both 0-1 and 0-100 scales
        if confidence <= 1:
            confidence_pct = round(confidence * 100)
        else:
            confidence_pct = round(confidence)

    context = {
        "investigation_id": investigation.get("investigation_id", "unknown"),
        "status": investigation.get("status", "unknown").upper(),
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        "root_cause": synthesis.get("root_cause"),
        "confidence": confidence,
        "confidence_pct": confidence_pct,
        "evidence": evidence,
        "recommendations": synthesis.get("recommendations", []),
    }

    return template.render(**context)
