"""Investigation export utilities for markdown and JSON report generation."""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from jinja2 import Environment

# Chain metadata constants
CHAIN_METADATA = {
    "hash_algorithm": "sha256",
    "canonicalization": "rfc8785",
    "chain_version": "evidence_v1",
}

# Markdown report template
MARKDOWN_TEMPLATE = """\
# Investigation Report: {{ investigation_id }}

**Status:** {{ status }}{% if confidence %} | **Confidence:** {{ confidence_pct }}%{% endif %}

**Generated:** {{ generated_at }}
{% if root_hash -%}
**Root Hash:** `{{ root_hash }}`
{% endif -%}
{% if has_chain_data -%}
**Chain Metadata:** algorithm={{ chain_metadata.hash_algorithm }}, \
canonicalization={{ chain_metadata.canonicalization }}, \
version={{ chain_metadata.chain_version }}
{% endif %}
---

## Summary

{% if root_cause -%}
{{ root_cause }}
{%- else -%}
_No root cause identified yet._
{%- endif %}

{% if related_code_changes -%}
## Related Code Changes

{% for change in related_code_changes -%}
{% if change.pr_number and change.pr_title -%}
- [PR #{{ change.pr_number }}: {{ change.pr_title }}]({{ change.url }})\
{% if change.author %} by {{ change.author }}{% endif %}

{% elif change.pr_number -%}
- [PR #{{ change.pr_number }}]({{ change.url }})\
{% if change.author %} by {{ change.author }}{% endif %}

{% else -%}
- [{{ change.commit_hash[:7] }}\
{% if change.message %}: {{ change.message[:50] }}\
{% if change.message|length > 50 %}...{% endif %}\
{% endif %}]({{ change.url }})\
{% if change.author %} by {{ change.author }}{% endif %}

{% endif -%}
{% endfor -%}
{% endif -%}

{% if evidence -%}
## Evidence Collected

{% for item in evidence -%}
### {{ loop.index }}. {{ item.kind | default("Evidence") | title | replace("_", " ") }}

{% if item.query or item.sql -%}
```sql
{{ item.query | default(item.sql) | truncate_sql }}
```

{% endif -%}
{% if item.interpretation -%}
**Interpretation:** {{ item.interpretation }}
{% endif -%}
{% if item.supports_hypothesis is not none -%}
**Verdict:** {{ "Supports" if item.supports_hypothesis else "Refutes" }} hypothesis
{% endif -%}
{% if item.confidence -%}
**Confidence:** {{ (item.confidence * 100) | round | int }}%
{% endif -%}
{% if item.seq -%}
**Chain:** seq={{ item.seq }}{% if item.content_hash %}, hash=`{{ item.content_hash[:16] }}...`\
{% endif %}{% if item.prev_hash %}, prev=`{{ item.prev_hash[:16] }}...`{% endif %}

{% endif %}

{% endfor -%}
{% else -%}
_No evidence collected yet._

{% endif -%}

{% if recommendations -%}
## Recommendations

{% for rec in recommendations -%}
- {{ rec }}
{% endfor %}
{% endif -%}

---

*Generated by Dataing CLI*
"""


def _truncate_sql(sql: str, max_length: int = 2000) -> str:
    """Truncate SQL query if too long.

    Args:
        sql: The SQL query string.
        max_length: Maximum length before truncation.

    Returns:
        Truncated SQL with marker if needed.
    """
    if len(sql) <= max_length:
        return sql
    return sql[:max_length] + "\n-- ... (truncated)"


def _has_chain_data(evidence: list[dict[str, Any]]) -> bool:
    """Check if any evidence item has hash chain fields.

    Args:
        evidence: List of evidence dictionaries.

    Returns:
        True if at least one item has content_hash.
    """
    return any(item.get("content_hash") for item in evidence)


def render_markdown(investigation: dict[str, Any]) -> str:
    """Render investigation data as markdown report.

    Args:
        investigation: Investigation state dict with fields:
            - investigation_id: str
            - status: str
            - root_hash: str | None
            - main_branch: dict with synthesis and evidence

    Returns:
        Formatted markdown string.
    """
    env = Environment(trim_blocks=True, lstrip_blocks=True)
    env.filters["truncate_sql"] = _truncate_sql
    template = env.from_string(MARKDOWN_TEMPLATE)

    # Extract data from investigation
    main_branch = investigation.get("main_branch", {})
    synthesis = main_branch.get("synthesis") or {}
    evidence = main_branch.get("evidence", [])

    # Get confidence and convert to percentage
    confidence = synthesis.get("confidence")
    confidence_pct = None
    if confidence is not None:
        # Handle both 0-1 and 0-100 scales
        if confidence <= 1:
            confidence_pct = round(confidence * 100)
        else:
            confidence_pct = round(confidence)

    has_chain = _has_chain_data(evidence)

    # Get related code changes (if available)
    related_code_changes = investigation.get("related_code_changes", [])
    # Also check synthesis for code changes
    if not related_code_changes and synthesis:
        related_code_changes = synthesis.get("related_code_changes", [])

    context = {
        "investigation_id": investigation.get("investigation_id", "unknown"),
        "status": investigation.get("status", "unknown").upper(),
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        "root_cause": synthesis.get("root_cause"),
        "confidence": confidence,
        "confidence_pct": confidence_pct,
        "evidence": evidence,
        "recommendations": synthesis.get("recommendations", []),
        "root_hash": investigation.get("root_hash"),
        "has_chain_data": has_chain,
        "chain_metadata": CHAIN_METADATA if has_chain else None,
        "related_code_changes": related_code_changes,
    }

    return template.render(**context)


def render_json(investigation: dict[str, Any]) -> str:
    """Render investigation data as JSON.

    Output structure matches the InvestigationStateResponse API schema
    with chain metadata for external verification.

    Args:
        investigation: Investigation state dict with fields:
            - investigation_id: str
            - status: str
            - root_hash: str | None
            - main_branch: dict with synthesis and evidence

    Returns:
        Formatted JSON string (indented for readability).
    """
    main_branch = investigation.get("main_branch", {})
    evidence = main_branch.get("evidence", [])
    has_chain = _has_chain_data(evidence)

    output: dict[str, Any] = {
        "investigation_id": investigation.get("investigation_id"),
        "status": investigation.get("status"),
        "generated_at": datetime.now().isoformat() + "Z",
        "root_hash": investigation.get("root_hash"),
        "main_branch": {
            "status": main_branch.get("status"),
            "current_step": main_branch.get("current_step"),
            "synthesis": main_branch.get("synthesis"),
            "evidence": evidence,
        },
    }

    if has_chain:
        output["chain_metadata"] = CHAIN_METADATA

    return json.dumps(output, indent=2, default=str)
