"""Investigation export utilities for markdown and JSON report generation."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from typing import Any

from jinja2 import Environment

# Markdown report template
MARKDOWN_TEMPLATE = """\
# Investigation Report: {{ investigation_id }}

**Status:** {{ status }}{% if confidence %} | **Confidence:** {{ confidence_pct }}%{% endif %}

**Generated:** {{ generated_at }}
{% if chain_hash -%}
**Evidence Chain Hash:** `{{ chain_hash }}`
{% endif %}
---

## Summary

{% if root_cause -%}
{{ root_cause }}
{%- else -%}
_No root cause identified yet._
{%- endif %}

{% if evidence -%}
## Evidence Collected

{% for item in evidence -%}
### {{ loop.index }}. {{ item.kind | default("Evidence") | title | replace("_", " ") }}

{% if item.query or item.sql -%}
```sql
{{ item.query | default(item.sql) | truncate_sql }}
```

{% endif -%}
{% if item.interpretation -%}
**Interpretation:** {{ item.interpretation }}
{% endif -%}
{% if item.supports_hypothesis is not none -%}
**Verdict:** {{ "Supports" if item.supports_hypothesis else "Refutes" }} hypothesis
{% endif -%}
{% if item.confidence -%}
**Confidence:** {{ (item.confidence * 100) | round | int }}%
{% endif %}

{% endfor -%}
{% else -%}
_No evidence collected yet._

{% endif -%}

{% if recommendations -%}
## Recommendations

{% for rec in recommendations -%}
- {{ rec }}
{% endfor %}
{% endif -%}

---

*Generated by Dataing CLI*
"""


def _truncate_sql(sql: str, max_length: int = 2000) -> str:
    """Truncate SQL query if too long.

    Args:
        sql: The SQL query string.
        max_length: Maximum length before truncation.

    Returns:
        Truncated SQL with marker if needed.
    """
    if len(sql) <= max_length:
        return sql
    return sql[:max_length] + "\n-- ... (truncated)"


def compute_chain_hash(evidence: list[dict[str, Any]]) -> str:
    """Compute SHA256 hash of evidence chain for audit.

    Uses canonical JSON (sorted keys, no whitespace) for deterministic hashing.

    Args:
        evidence: List of evidence dictionaries.

    Returns:
        64-character hexadecimal SHA256 hash string.
    """
    if not evidence:
        return hashlib.sha256(b"[]").hexdigest()
    canonical = json.dumps(evidence, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canonical.encode()).hexdigest()


def render_markdown(investigation: dict[str, Any]) -> str:
    """Render investigation data as markdown report.

    Args:
        investigation: Investigation state dict with fields:
            - investigation_id: str
            - status: str
            - main_branch: dict with synthesis and evidence

    Returns:
        Formatted markdown string.
    """
    env = Environment(trim_blocks=True, lstrip_blocks=True)
    env.filters["truncate_sql"] = _truncate_sql
    template = env.from_string(MARKDOWN_TEMPLATE)

    # Extract data from investigation
    main_branch = investigation.get("main_branch", {})
    synthesis = main_branch.get("synthesis") or {}
    evidence = main_branch.get("evidence", [])

    # Get confidence and convert to percentage
    confidence = synthesis.get("confidence")
    confidence_pct = None
    if confidence is not None:
        # Handle both 0-1 and 0-100 scales
        if confidence <= 1:
            confidence_pct = round(confidence * 100)
        else:
            confidence_pct = round(confidence)

    # Compute evidence chain hash
    chain_hash = compute_chain_hash(evidence)

    context = {
        "investigation_id": investigation.get("investigation_id", "unknown"),
        "status": investigation.get("status", "unknown").upper(),
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        "root_cause": synthesis.get("root_cause"),
        "confidence": confidence,
        "confidence_pct": confidence_pct,
        "evidence": evidence,
        "recommendations": synthesis.get("recommendations", []),
        "chain_hash": chain_hash,
    }

    return template.render(**context)


def render_json(investigation: dict[str, Any]) -> str:
    """Render investigation data as JSON.

    Output structure matches the InvestigationStateResponse API schema
    with an added chain_hash field for audit.

    Args:
        investigation: Investigation state dict with fields:
            - investigation_id: str
            - status: str
            - main_branch: dict with synthesis and evidence

    Returns:
        Formatted JSON string (indented for readability).
    """
    main_branch = investigation.get("main_branch", {})
    evidence = main_branch.get("evidence", [])

    # Compute evidence chain hash
    chain_hash = compute_chain_hash(evidence)

    output = {
        "investigation_id": investigation.get("investigation_id"),
        "status": investigation.get("status"),
        "chain_hash": chain_hash,
        "generated_at": datetime.now().isoformat() + "Z",
        "main_branch": {
            "status": main_branch.get("status"),
            "current_step": main_branch.get("current_step"),
            "synthesis": main_branch.get("synthesis"),
            "evidence": evidence,
        },
    }

    return json.dumps(output, indent=2, default=str)
