name: DCO

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read
  contents: read

jobs:
  check:
    name: DCO Sign-off Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check DCO
        uses: dcoapp/app-github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
